-- SRS schema snapshot for EPROC00110.
-- Evidence comes from docs/db-diff/02_tables/*.md and current source usage.
-- This file is not a migration script; it lists contract-relevant tables/columns.
-- Checkpoint polarity for visible EPROC00110 child pages:
-- 'Y' = pending / still needs work, 'N' = completed.
-- The physical DB default 'N' is not the active-frame initialization rule.
-- General 0110 vs renewal/change 0210 provenance is runtime-only. db-diff
-- maps legacy general and RC checkpoint tables into the same active
-- TB_CHECK_POINTS_CS/CU tables, each keyed only by APPLICATION_NO; use
-- sourceFrame/sourceTabMap for 011x/021x provenance, not a DB discriminator.
-- EPROCSU0160 exists physically in TB_CHECK_POINTS_CS/CU as Loan Condition,
-- but is intentionally excluded from this EPROC00110 contract schema.

CREATE TABLE TB_LON_SUMMARY_INFO (
    APPLICATION_NO VARCHAR2(30) NOT NULL,
    LON_TYPE_CODE VARCHAR2(5),
    PRODUCT_CODE VARCHAR2(5),
    LON_ATTRIBUTE VARCHAR2(2),
    SECURE_ATTRIBUTE VARCHAR2(2),
    ASSESSMENT_TYPE VARCHAR2(1),
    BUSINESS_TYPE VARCHAR2(1),
    CR_SCORE_CARD_COMPLETED VARCHAR2(2),
    CONSTRAINT PK_TB_LON_SUMMARY_INFO PRIMARY KEY (APPLICATION_NO)
);

CREATE TABLE TB_CHECK_POINTS_CS (
    APPLICATION_NO VARCHAR2(30) NOT NULL,
    EPROC00115 VARCHAR2(2) DEFAULT 'N',
    EPROC00112 VARCHAR2(2) DEFAULT 'N',
    EPROC00116 VARCHAR2(2) DEFAULT 'N',
    EPROC00119 VARCHAR2(2) DEFAULT 'N',
    EPROC00117 VARCHAR2(2) DEFAULT 'N',
    EPROC00120 VARCHAR2(2) DEFAULT 'N',
    EPROC00118 VARCHAR2(2) DEFAULT 'N',
    EPROC00114 VARCHAR2(2) DEFAULT 'N',
    CONSTRAINT PK_TB_CHECK_POINTS_CS PRIMARY KEY (APPLICATION_NO)
);

CREATE TABLE TB_CHECK_POINTS_CU (
    APPLICATION_NO VARCHAR2(30) NOT NULL,
    EPROC00115 VARCHAR2(2) DEFAULT 'N',
    EPROC00112 VARCHAR2(2) DEFAULT 'N',
    EPROC00116 VARCHAR2(2) DEFAULT 'N',
    EPROC00119 VARCHAR2(2) DEFAULT 'N',
    EPROC00117 VARCHAR2(2) DEFAULT 'N',
    EPROC00120 VARCHAR2(2) DEFAULT 'N',
    EPROC00118 VARCHAR2(2) DEFAULT 'N',
    CONSTRAINT PK_TB_CHECK_POINTS_CU PRIMARY KEY (APPLICATION_NO)
);

-- R8 destructive-switch clearing targets.
-- Triage: group-21/group-23/TB_CORP_SCRCARD remain active new DB tables;
-- the behavior delta is transactional delete-on-switch plus checkpoint reset,
-- not schema removal. Sources: docs/db-diff/01_groups/group-21.md:13-17,
-- docs/db-diff/01_groups/group-23.md:13-19,
-- docs/db-diff/02_tables/TB_CORP_SCRCARD.md:13-16.
CREATE TABLE TB_FINANCIAL_EVALUATION_GI (
    APPLICATION_NO VARCHAR2(30) NOT NULL,
    DATA_SEQ NUMBER(2),
    CONSTRAINT PK_TB_FINANCIAL_EVALUATION_GI PRIMARY KEY (APPLICATION_NO, DATA_SEQ)
);

CREATE TABLE TB_FINANCIAL_EVALUATION_FI (
    APPLICATION_NO VARCHAR2(30) NOT NULL,
    DATA_SEQ VARCHAR2(2) NOT NULL,
    CONSTRAINT PK_TB_FINANCIAL_EVALUATION_FI PRIMARY KEY (APPLICATION_NO, DATA_SEQ)
);

CREATE TABLE TB_FIN_STATEMENT_MAIN (
    APPLICATION_NO VARCHAR2(30) NOT NULL,
    CURRENCY VARCHAR2(3) NOT NULL,
    CONSTRAINT PK_TB_FIN_STATEMENT_MAIN PRIMARY KEY (APPLICATION_NO)
);

CREATE TABLE TB_FIN_STATEMENT_BALANCE_GI (
    APPLICATION_NO VARCHAR2(30) NOT NULL,
    DATA_SEQ NUMBER(2),
    CONSTRAINT PK_TB_FIN_STATEMENT_BAL_GI PRIMARY KEY (APPLICATION_NO, DATA_SEQ)
);

-- FI financial-statement table key metadata is incomplete in db-diff.
-- R8 only contracts these tables as destructive-switch delete targets by
-- APPLICATION_NO; no PK/NOT NULL contract is asserted here for FI detail rows.
-- Sources: TB_FIN_STATEMENT_BALANCE_FI.md:32,38-39;
-- TB_FIN_STATEMENT_CASHFLOW_FI.md:32; TB_FIN_STATEMENT_INCOME_FI.md:32,38-39.
CREATE TABLE TB_FIN_STATEMENT_BALANCE_FI (
    APPLICATION_NO VARCHAR2(30),
    DATA_SEQ NUMBER(2)
);

CREATE TABLE TB_FIN_STATEMENT_CASHFLOW_GI (
    APPLICATION_NO VARCHAR2(30) NOT NULL,
    DATA_SEQ NUMBER(2),
    CONSTRAINT PK_TB_FIN_STATEMENT_CASH_GI PRIMARY KEY (APPLICATION_NO, DATA_SEQ)
);

CREATE TABLE TB_FIN_STATEMENT_CASHFLOW_FI (
    APPLICATION_NO VARCHAR2(30),
    DATA_SEQ NUMBER(2)
);

CREATE TABLE TB_FIN_STATEMENT_INCOME_GI (
    APPLICATION_NO VARCHAR2(30) NOT NULL,
    DATA_SEQ NUMBER(2),
    CONSTRAINT PK_TB_FIN_STATEMENT_INC_GI PRIMARY KEY (APPLICATION_NO, DATA_SEQ)
);

CREATE TABLE TB_FIN_STATEMENT_INCOME_FI (
    APPLICATION_NO VARCHAR2(30),
    DATA_SEQ NUMBER(2)
);

-- Corporate scorecard is also cleared by R8 destructive switch.
-- Source: docs/db-diff/02_tables/TB_CORP_SCRCARD.md:13-16.
CREATE TABLE TB_CORP_SCRCARD (
    APPLICATION_NO VARCHAR2(30) NOT NULL,
    AO_SCORE NUMBER(7,2),
    CR_SCORE NUMBER(7,2),
    CR_DATE TIMESTAMP(6),
    CONSTRAINT PK_TB_CORP_SCRCARD PRIMARY KEY (APPLICATION_NO)
);

-- Legacy checkpoint tables referenced for parity only:
-- TB_CHECK_POINT_CORP was transferred to TB_CHECK_POINTS_CS.
-- TB_CHECK_POINT_CU was transferred to TB_CHECK_POINTS_CU.
-- TB_CHECK_POINT_RC_CORP was transferred to TB_CHECK_POINTS_CS.
-- TB_CHECK_POINT_RC_CU was transferred to TB_CHECK_POINTS_CU.

-- Authorization seed boundary referenced by R12; service-level edit/old-case
-- authorization remains required above this seed table.
-- Source: docs/db-diff/02_tables/TB_API_AUTH.md:36-42.
CREATE TABLE TB_API_AUTH (
    API_ID VARCHAR2(100 BYTE) NOT NULL,
    ROLE VARCHAR2(100 BYTE) NOT NULL,
    REF_FUNCTION_ID VARCHAR2(100 BYTE),
    UPDATE_USER VARCHAR2(10 BYTE),
    UPDATE_DATE DATE,
    CONSTRAINT PK_TB_API_AUTH PRIMARY KEY (API_ID)
);
