-- EPROISU0921 Data Input relevant physical-column subset.
-- Column types/lengths shown here come from docs/db-diff/02_tables/*.md.
-- Omitted table columns remain governed by db-diff and are outside this bundle's contract.
-- This is not a migration script.

CREATE TABLE TB_LON_SUMMARY_INFO (
  APPLICATION_NO VARCHAR2(30) NOT NULL,
  LON_TYPE_CODE VARCHAR2(5),
  PRODUCT_CODE VARCHAR2(5),
  LON_APP_CURRENCY VARCHAR2(3),
  LON_APP_AMT NUMBER(17,2),
  APPLICATION_DATE TIMESTAMP(6),
  RECEIVED_DATE TIMESTAMP(6),
  CASE_PROGRESS VARCHAR2(5),
  LON_ATTRIBUTE VARCHAR2(2),
  SECURE_ATTRIBUTE VARCHAR2(2),
  BRANCH_CODE VARCHAR2(10),
  SYSTEM_VER VARCHAR2(5),
  CADM_CODE VARCHAR2(7),
  CADC_CODE VARCHAR2(7),
  DISBURSING_DATE TIMESTAMP(6),
  PRIMARY KEY (APPLICATION_NO)
);

CREATE TABLE TB_DISBUR_DATE (
  APPLICATION_NO VARCHAR2(30) NOT NULL,
  GROUP_BORROWER VARCHAR2(20),
  BORROWER_T24_NO VARCHAR2(30),
  CBC_MEMBER VARCHAR2(30),
  CBC_MEMBER_1 VARCHAR2(5),
  CBC_MEMBER_2 VARCHAR2(5),
  CBC_MEMBER_3 VARCHAR2(5),
  CBC_MEMBER_4 VARCHAR2(5),
  CBC_SPECIAL VARCHAR2(5),
  AGREEMENT_NO VARCHAR2(30),
  DISBURSEMENT_CURRENCY VARCHAR2(3),
  DISBURSEMENT_AMOUNT NUMBER(17,2),
  DES_REP_DAY NUMBER(2,0),
  DRAWDOWN_ACCOINT DATE,
  DISBURSEMENT_BY VARCHAR2(25),
  LAW_FIRM_NO VARCHAR2(5),
  LAW_FIRM_AMOUNT NUMBER(17,2),
  EPORIS_0921 VARCHAR2(5),
  FACILITY_FEE NUMBER(17,2),
  REFINANCING_FEE NUMBER(17,2),
  EX_RATE_BUY NUMBER(17,2),
  EX_RATE_SELL NUMBER(17,2),
  NEXT_KEY VARCHAR2(100),
  CUBC_RELATED_CIF_NO VARCHAR2(10),
  LAW_FIRM_AMOUNT_01 NUMBER(17,2),
  LAW_FIRM_AMOUNT_02 NUMBER(17,2),
  LAW_FIRM_AMOUNT_03 NUMBER(17,2),
  LAW_FIRM_AMOUNT_90 NUMBER(17,2),
  LAW_FIRM_90_OTHER_REMARK VARCHAR2(16),
  PRIMARY KEY (APPLICATION_NO)
);

CREATE TABLE TB_DISBUR_COLL (
  APPLICATION_NO VARCHAR2(30) NOT NULL,
  COLL_DATA_SEQ NUMBER(3,0) NOT NULL,
  INS_BORROWER VARCHAR2(1),
  INS_COMPANY VARCHAR2(10),
  INS_BORROWERY_SELECT VARCHAR2(5),
  INS_START_DATE DATE,
  INS_EXPIRY_DATE DATE,
  POLICY_NUMBER VARCHAR2(30),
  INSURANCE_AMOUNT NUMBER(17,2),
  PROPERTY_COLL VARCHAR2(1),
  COLL_PROVINCE_CODE VARCHAR2(5),
  COLL_DISTRICT_CODE VARCHAR2(5),
  COLL_COMMUNE_CODE VARCHAR2(8),
  COLL_VILLAGE_CODE VARCHAR2(8),
  COLL_ADDR_RS VARCHAR2(210),
  COLL_ADDR_LAST VARCHAR2(210),
  PUR_PRO_TYPE VARCHAR2(5),
  EST_COM_DATE DATE,
  TITLE_PURC_PRO VARCHAR2(5),
  PRICE_PROPERTY NUMBER(17,2),
  PRICE_LAND NUMBER(17,2),
  SUG_VAL NUMBER(17,2),
  BUILT_WIDTH NUMBER(17,2),
  BUILD_AREA NUMBER(17,2),
  LAND_AREA NUMBER(17,2),
  BUILT_FLOOR VARCHAR2(5),
  BUILT_BEDROOM VARCHAR2(5),
  PUR_OF_LOAN_NBC VARCHAR2(5),
  PUR_OF_LOAN_NBC_OTHER VARCHAR2(210),
  EST_COM_TYPE VARCHAR2(7),
  PRIMARY KEY (APPLICATION_NO, COLL_DATA_SEQ)
);

CREATE TABLE TB_DISBUR_OTHER_COLL (
  APPLICATION_NO VARCHAR2(30) NOT NULL,
  OTHER_COLL_DATA_SEQ NUMBER(3,0) NOT NULL,
  OTHER_COLL_PROVINCE_CODE VARCHAR2(5),
  OTHER_COLL_DISTRICT_CODE VARCHAR2(5),
  OTHER_COLL_COMMUNE_CODE VARCHAR2(8),
  OTHER_COLL_VILLAGE_CODE VARCHAR2(8),
  OTHER_COLL_ADDR_RS VARCHAR2(210),
  OTHER_COLL_ADDR_LAST VARCHAR2(210),
  OTHER_PUR_PRO_TYPE VARCHAR2(5),
  OTHER_EST_COM_DATE DATE,
  OTHER_TITLE_PURC_PRO VARCHAR2(5),
  OTHER_PRICE_PROPERTY NUMBER(17,2),
  OTHER_PRICE_LAND NUMBER(17,2),
  OTHER_SUG_VAL NUMBER(17,2),
  OTHER_BUILT_WIDTH NUMBER(17,2),
  OTHER_BUILD_AREA NUMBER(17,2),
  OTHER_LAND_AREA NUMBER(17,2),
  OTHER_BUILT_FLOOR VARCHAR2(5),
  OTHER_BUILT_BEDROOM VARCHAR2(5),
  OTHER_PUR_OF_LOAN_NBC VARCHAR2(5),
  OTHER_PUR_OF_LOAN_NBC_OTHER VARCHAR2(210),
  OTHER_EST_COM_TYPE VARCHAR2(7),
  PRIMARY KEY (APPLICATION_NO, OTHER_COLL_DATA_SEQ)
);

CREATE TABLE TB_T24_MAIN_BORROWER_INFO (
  APPLICATION_NO VARCHAR2(30) NOT NULL,
  RECID VARCHAR2(10) NOT NULL,
  CHECK_DATE TIMESTAMP(6),
  FULL_NAME VARCHAR2(140),
  GENDER VARCHAR2(35),
  DATE_OF_BIRTH DATE,
  SECTOR VARCHAR2(35),
  INDUSTRY VARCHAR2(35),
  CHECK_SUCCESS VARCHAR2(5),
  BUSINESS_SEC_CODE VARCHAR2(7),
  PRIMARY KEY (APPLICATION_NO, RECID)
);

CREATE TABLE TB_T24_CO_BORROWER_INFO (
  APPLICATION_NO VARCHAR2(30) NOT NULL,
  RECID VARCHAR2(10) NOT NULL,
  DATA_SEQ NUMBER(2,0) NOT NULL,
  CHECK_DATE TIMESTAMP(6),
  FULL_NAME VARCHAR2(140),
  GENDER VARCHAR2(35),
  DATE_OF_BIRTH DATE,
  SECTOR VARCHAR2(35),
  INDUSTRY VARCHAR2(35),
  BUSINESS_SEC_CODE VARCHAR2(7),
  CHECK_SUCCESS VARCHAR2(5),
  PRIMARY KEY (APPLICATION_NO, RECID, DATA_SEQ)
);

CREATE TABLE TB_MAIN_BORROWER_ACC (
  APPLICATION_NO VARCHAR2(30) NOT NULL,
  RECID VARCHAR2(10) NOT NULL,
  DATA_SEQ VARCHAR2(3) NOT NULL,
  ACCTID VARCHAR2(25),
  CATEGORY VARCHAR2(5),
  CURRENCY VARCHAR2(3),
  WORKINGBALANCE VARCHAR2(35),
  IS_SSI VARCHAR2(3),
  PRIMARY KEY (APPLICATION_NO, RECID, DATA_SEQ)
);

CREATE TABLE TB_LAW_FIRM (
  LAW_ACCOUNT_MUN VARCHAR2(36) NOT NULL,
  LAW_FIRM_NAME VARCHAR2(50) NOT NULL,
  LAW_ACCOUNT_NAME VARCHAR2(50) NOT NULL,
  LAW_SER_NO NUMBER(4,0) NOT NULL,
  IS_SHOW VARCHAR2(3) NOT NULL,
  PRIMARY KEY (LAW_ACCOUNT_MUN)
);

CREATE TABLE TB_PROVINCE (
  PROVINCE_CODE VARCHAR2(5) NOT NULL,
  PROVINCE_NAME VARCHAR2(50),
  SEQ_NO NUMBER(3,0),
  UPD_DATE DATE NOT NULL,
  PROVINCE_NAME_KH VARCHAR2(50) NOT NULL,
  PRIMARY KEY (PROVINCE_CODE, UPD_DATE)
);

CREATE TABLE TB_DISTRICT (
  PROVINCE_CODE VARCHAR2(5) NOT NULL,
  DISTRICT_CODE VARCHAR2(5) NOT NULL,
  DISTRICT_NAME VARCHAR2(50),
  SEQ_NO NUMBER(3,0),
  UPD_DATE DATE NOT NULL,
  PRIMARY KEY (PROVINCE_CODE, DISTRICT_CODE, UPD_DATE)
);

CREATE TABLE TB_COMMUNE (
  DISTRICT_CODE VARCHAR2(5) NOT NULL,
  COMMUNE_CODE VARCHAR2(8) NOT NULL,
  COMMUNE_NAME VARCHAR2(50),
  SEQ_NO NUMBER(3,0),
  UPD_DATE DATE NOT NULL,
  PRIMARY KEY (DISTRICT_CODE, COMMUNE_CODE, UPD_DATE)
);

CREATE TABLE TB_VILLAGE (
  COMMUNE_CODE VARCHAR2(8) NOT NULL,
  VILLAGE_CODE VARCHAR2(8) NOT NULL,
  VILLAGE_NAME VARCHAR2(50),
  SEQ_NO NUMBER(3,0),
  UPD_DATE DATE NOT NULL,
  PRIMARY KEY (COMMUNE_CODE, VILLAGE_CODE, UPD_DATE)
);

CREATE TABLE TB_APP_HISTORY (
  APPLICATION_NO VARCHAR2(30) NOT NULL,
  APP_PROCESS_CODE VARCHAR2(5) NOT NULL,
  PROCESS_EMP_CODE VARCHAR2(7),
  PROCESS_EMP_NAME VARCHAR2(50),
  PROCESS_BRANCH_CODE VARCHAR2(5),
  PROCESS_BRANCH_NAME VARCHAR2(50),
  PROCESS_DATE TIMESTAMP(6) NOT NULL,
  PRIMARY KEY (APPLICATION_NO, APP_PROCESS_CODE, PROCESS_DATE)
);

CREATE TABLE TB_CONTR_DATA (
  APPLICATION_NO VARCHAR2(30) NOT NULL,
  CONTR_STATUS VARCHAR2(5),
  CHECK_AUTO_CONTR VARCHAR2(5),
  PRIMARY KEY (APPLICATION_NO)
);

CREATE TABLE TB_CONTR_AUTO_FILE_PTH (
  APPLICATION_NO VARCHAR2(30) NOT NULL,
  CONTR_DATA_SEQ VARCHAR2(30) NOT NULL,
  CONTR_FILE_NAME VARCHAR2(1000) NOT NULL,
  CONTR_AUTO_PATH VARCHAR2(500) NOT NULL,
  PRIMARY KEY (APPLICATION_NO, CONTR_DATA_SEQ)
);

CREATE TABLE TB_LOAN_CONDITION_FEE (
  APPLICATION_NO VARCHAR2(30) NOT NULL,
  CON_TYPE VARCHAR2(5) NOT NULL,
  ORI_APPLICATION_NO VARCHAR2(30),
  ORI_CON_TYPE VARCHAR2(5),
  PRIMARY KEY (APPLICATION_NO, CON_TYPE)
);

CREATE TABLE TB_LOAN_CONDITION_DETAIL (
  APPLICATION_NO VARCHAR2(30) NOT NULL,
  CON_TYPE VARCHAR2(5) NOT NULL,
  SEQNO NUMBER(3,0) NOT NULL,
  ORI_APPLICATION_NO VARCHAR2(30),
  ORI_CON_TYPE VARCHAR2(5),
  ORI_SEQNO NUMBER(3,0),
  PRIMARY KEY (APPLICATION_NO, CON_TYPE, SEQNO)
);

CREATE TABLE TB_API_AUTH (
  API_ID VARCHAR2(100) NOT NULL,
  ROLE VARCHAR2(100) NOT NULL,
  REF_FUNCTION_ID VARCHAR2(100),
  UPDATE_USER VARCHAR2(10),
  UPDATE_DATE DATE,
  PRIMARY KEY (API_ID)
);

-- 新舊對照 / reconcile notes:
-- legacy APPLICATION_NO -> applicationNo, unchanged physical key.
-- legacy EPORIS_0921 -> API eprois0921, physical typo preserved.
-- legacy DRAWDOWN_ACCOINT -> API drawdownAccount, physical typo preserved per db-diff.
-- legacy EST_COM_DATE -> collList[].estCom, must persist to TB_DISBUR_COLL.EST_COM_DATE.
-- legacy OTHER_EST_COM_DATE -> purPropList[].otrEstCom, must persist to TB_DISBUR_OTHER_COLL.OTHER_EST_COM_DATE.
-- legacy CO_CHECK/MB_CHECK -> API coCheck/mbCheck, backend authoritative for Finished.
-- legacy address UPD_DATE -> API updDate, sourced from application-date convention.
