-- EPROISU0922 schema snapshot and change hints.
-- Source: local docs/db-diff/02_tables/*.md. This file is not a migration.

CREATE TABLE TB_LON_SUMMARY_INFO (
  APPLICATION_NO VARCHAR2(30 BYTE) NOT NULL,
  DECISION_DATE TIMESTAMP(6),
  CASE_PROGRESS VARCHAR2(5 BYTE),
  CURRENT_USER_ID VARCHAR2(7 BYTE),
  CADC_CODE VARCHAR2(7 BYTE),
  DISBURSING_DATE TIMESTAMP(6),
  SECURE_ATTRIBUTE VARCHAR2(2 BYTE),
  DEP_CODE VARCHAR2(5 BYTE),
  FIN_CON_TYPE VARCHAR2(5 BYTE),
  IS_AUTODIS VARCHAR2(2 BYTE),
  CONSTRAINT PK_TB_LON_SUMMARY_INFO PRIMARY KEY (APPLICATION_NO)
);
-- change-hint: active/exact; transpose_method says copy existing data and modify fields.
-- EPROISU0922 updates CASE_PROGRESS 24/25/26/27/C1 and DISBURSING_DATE.

CREATE TABLE TB_DISBUR_DATE (
  APPLICATION_NO VARCHAR2(30 BYTE) NOT NULL,
  BORROWER_T24_NO VARCHAR2(30 BYTE),
  AGREEMENT_NO VARCHAR2(30 BYTE),
  DISBURSEMENT_CURRENCY VARCHAR2(3 BYTE),
  DISBURSEMENT_AMOUNT NUMBER(17,2),
  DRAWDOWN_ACCOINT DATE,
  LAW_FIRM_AMOUNT NUMBER(17,2),
  FACILITY_FEE NUMBER(17,2),
  REFINANCING_FEE NUMBER(17,2),
  LAW_FIRM_AMOUNT_01 NUMBER(17,2),
  LAW_FIRM_AMOUNT_02 NUMBER(17,2),
  LAW_FIRM_AMOUNT_03 NUMBER(17,2),
  LAW_FIRM_AMOUNT_90 NUMBER(17,2),
  EX_RATE_BUY NUMBER(17,2),
  EX_RATE_SELL NUMBER(17,2),
  DES_REP_DAY NUMBER(2,0),
  LAW_FIRM_90_OTHER_REMARK VARCHAR2(16 BYTE),
  CUBC_RELATED_CIF_NO VARCHAR2(10 BYTE),
  CONSTRAINT PK_TB_DISBUR_DATE PRIMARY KEY (APPLICATION_NO)
);
-- change-hint: active/exact; Ver 02.10 Add; money fields are NUMBER(17,2).
-- T24 contract must preserve rate/money precision and any T24-specific truncation evidence.
-- T24 A31/G7 use AGREEMENT_NO rightmost 16 characters only in file output; DB keeps VARCHAR2(30 BYTE).
-- T24 law-firm fee rows may read LAW_FIRM_AMOUNT_01/02/03/90 and LAW_FIRM_90_OTHER_REMARK.
-- T24 G4/H4 and G10/H8 use DISBURSEMENT_CURRENCY as the currency source; G10/H8 use EX_RATE_BUY only when that source is KHR.

CREATE TABLE TB_LOAN_CONDITION_FEE (
  APPLICATION_NO VARCHAR2(30 BYTE) NOT NULL,
  CON_TYPE VARCHAR2(5 BYTE) NOT NULL,
  CBC_FEE VARCHAR2(300 BYTE),
  CONSTRAINT PK_TB_LOAN_CONDITION_FEE PRIMARY KEY (APPLICATION_NO, CON_TYPE)
);
-- change-hint: active/exact; copied from existing data; E21 reads CBC_FEE.
-- CBC_FEE is text in DB, so KHR E21 generation must parse it explicitly and fail on invalid numeric content.

CREATE TABLE TB_DISBUR_COLL (
  APPLICATION_NO VARCHAR2(30 BYTE) NOT NULL,
  COLL_DATA_SEQ NUMBER(3,0) NOT NULL,
  INS_START_DATE DATE,
  INS_EXPIRY_DATE DATE,
  INSURANCE_AMOUNT NUMBER(17,2),
  PRICE_PROPERTY NUMBER(17,2),
  PRICE_LAND NUMBER(17,2),
  SUG_VAL NUMBER(17,2),
  BUILT_WIDTH NUMBER(17,2),
  BUILD_AREA NUMBER(17,2),
  LAND_AREA NUMBER(17,2),
  CONSTRAINT PK_TB_DISBUR_COLL PRIMARY KEY (APPLICATION_NO, COLL_DATA_SEQ)
);
-- change-hint: active/exact; copied from existing data; sequence is part of PK.
-- T24 C20 reads INS_EXPIRY_DATE for the current COLL_DATA_SEQ; INS_END_DATE is not a valid source column.

CREATE TABLE TB_DISBUR_OTHER_COLL (
  APPLICATION_NO VARCHAR2(30 BYTE) NOT NULL,
  OTHER_COLL_DATA_SEQ NUMBER(3,0) NOT NULL,
  OTHER_PRICE_PROPERTY NUMBER(17,2),
  OTHER_PRICE_LAND NUMBER(17,2),
  OTHER_SUG_VAL NUMBER(17,2),
  OTHER_BUILT_WIDTH NUMBER(17,2),
  OTHER_BUILD_AREA NUMBER(17,2),
  OTHER_LAND_AREA NUMBER(17,2),
  CONSTRAINT PK_TB_DISBUR_OTHER_COLL PRIMARY KEY (APPLICATION_NO, OTHER_COLL_DATA_SEQ)
);
-- change-hint: active/exact; copied from existing data; sequence is part of PK.

CREATE TABLE TB_COLL_VALUE_INFO (
  APPLICATION_NO VARCHAR2(30 BYTE) NOT NULL,
  COLL_DATA_SEQ NUMBER(3,0) NOT NULL,
  SUG_VAL NUMBER(19,2),
  CONSTRAINT PK_TB_COLL_VALUE_INFO PRIMARY KEY (APPLICATION_NO, COLL_DATA_SEQ)
);
-- change-hint: active/exact; T24 C12 reads sequence-specific SUG_VAL from valuation info, not the C-row collateral map.

CREATE TABLE TB_COLL_TITLE_DETAIL (
  APPLICATION_NO VARCHAR2(30 BYTE) NOT NULL,
  COLL_DATA_SEQ NUMBER(3,0) NOT NULL,
  COLL_DOC_SEQ NUMBER(3,0) NOT NULL,
  TITLE_DEED_NO VARCHAR2(100 BYTE),
  CONSTRAINT PK_TB_COLL_TITLE_DETAIL PRIMARY KEY (APPLICATION_NO, COLL_DATA_SEQ, COLL_DOC_SEQ)
);
-- change-hint: active/exact; T24 C26 reads only TITLE_DEED_NO rows for the current COLL_DATA_SEQ and joins them with '|'.

CREATE TABLE TB_MAIN_BORROWER_PERSONAL_INFO (
  APPLICATION_NO VARCHAR2(30 BYTE) NOT NULL,
  MAIN_BORROWER_NAME VARCHAR2(50 BYTE) NOT NULL,
  RESIDENT_PROVINCE_CODE VARCHAR2(5 BYTE),
  RESIDENT_DISTRICT_CODE VARCHAR2(5 BYTE),
  CONSTRAINT PK_TB_MAIN_BORROWER_PERSONAL_INFO PRIMARY KEY (APPLICATION_NO, MAIN_BORROWER_NAME)
);
-- change-hint: active/exact; T24 A52 uses the main borrower's resident province/district code.

CREATE TABLE TB_DISTRICT (
  PROVINCE_CODE VARCHAR2(5 BYTE) NOT NULL,
  DISTRICT_CODE VARCHAR2(5 BYTE) NOT NULL,
  UPD_DATE DATE NOT NULL,
  DISTRICT_NAME VARCHAR2(50 BYTE),
  CONSTRAINT PK_TB_DISTRICT PRIMARY KEY (PROVINCE_CODE, DISTRICT_CODE, UPD_DATE)
);
-- change-hint: active/exact; T24 A52 reads DISTRICT_NAME using the existing disbursing-date UPD_DATE convention.

CREATE TABLE TB_MESS_UPLOAD_SFTP_RECORD (
  APPLICATION_NO VARCHAR2(30 BYTE) NOT NULL,
  UPLOAD_FILE_NAME VARCHAR2(100 BYTE) NOT NULL,
  UPLOAD_SAVE_FILE VARCHAR2(2000 BYTE),
  UPLOAD_EXCUTE_TIME TIMESTAMP(6),
  CONSTRAINT PK_TB_MESS_UPLOAD_SFTP_RECORD PRIMARY KEY (APPLICATION_NO)
);
-- change-hint: active/exact; records generated T24 file upload evidence.

CREATE TABLE TB_MESS_RECORD (
  APPLICATION_NO VARCHAR2(30 BYTE) NOT NULL,
  DATA_SEQ NUMBER(3,0) NOT NULL,
  MESSAGE_CODE VARCHAR2(35 BYTE),
  REFERENCE_NO VARCHAR2(35 BYTE),
  STATUS VARCHAR2(5 BYTE),
  ERROR_CODE VARCHAR2(35 BYTE),
  VALUE_DATE TIMESTAMP(6),
  REFERENCE_REMARK VARCHAR2(35 BYTE),
  CONSTRAINT PK_TB_MESS_RECORD PRIMARY KEY (APPLICATION_NO, DATA_SEQ)
);
-- change-hint: active/exact; stores T24 deal result parsed rows.

CREATE TABLE TB_APP_HISTORY (
  APPLICATION_NO VARCHAR2(30 BYTE) NOT NULL,
  APP_PROCESS_CODE VARCHAR2(5 BYTE) NOT NULL,
  PROCESS_EMP_CODE VARCHAR2(7 BYTE),
  PROCESS_EMP_NAME VARCHAR2(50 BYTE),
  PROCESS_DATE TIMESTAMP(6) NOT NULL,
  CONSTRAINT PK_TB_APP_HISTORY PRIMARY KEY (APPLICATION_NO, APP_PROCESS_CODE, PROCESS_DATE)
);
-- change-hint: active/exact; state transition history for submit/return/authorize/result.

CREATE TABLE TB_NOTIFICATION_INFO (
  NO NUMBER NOT NULL,
  APPLICATION_NO VARCHAR2(30 BYTE) NOT NULL,
  RECEIVER_ID VARCHAR2(5 BYTE) NOT NULL,
  RECEIVER_NAME VARCHAR2(50 BYTE),
  RECEIVER_EMAIL VARCHAR2(100 BYTE),
  STATUS VARCHAR2(1 BYTE) DEFAULT 'N',
  CONSTRAINT PK_TB_NOTIFICATION_INFO PRIMARY KEY (NO, APPLICATION_NO)
);
-- change-hint: active/exact; submit/return persist notification tasks atomically, while async email delivery/retry is owned by the shared notification mechanism.

CREATE TABLE TB_EMP_PROXY (
  EMP_ID VARCHAR2(10 BYTE) NOT NULL,
  PROXY_ID VARCHAR2(10 BYTE),
  STR_TIME TIMESTAMP(6) NOT NULL,
  END_TIME TIMESTAMP(6),
  RETURN_CASE_TO_CA VARCHAR2(1 BYTE) DEFAULT 'N',
  CONSTRAINT PK_TB_EMP_PROXY PRIMARY KEY (EMP_ID)
);
-- change-hint: active/exact; submit/return read proxy recipients for notification tasks and do not mutate this table.

CREATE TABLE TB_API_AUTH (
  API_ID VARCHAR2(100 BYTE) NOT NULL,
  ROLE VARCHAR2(100 BYTE) NOT NULL,
  REF_FUNCTION_ID VARCHAR2(100 BYTE),
  UPDATE_USER VARCHAR2(10 BYTE),
  UPDATE_DATE DATE,
  CONSTRAINT PK_TB_API_AUTH PRIMARY KEY (API_ID)
);
-- change-hint: active/exact; note says refactor-added and transpose_method is rewrite.
-- Authorization seed rows do not replace BE service-level guards.

CREATE TABLE TB_T24_MAIN_BORROWER_INFO (
  APPLICATION_NO VARCHAR2(30 BYTE) NOT NULL,
  RECID VARCHAR2(10 BYTE) NOT NULL,
  CHECK_DATE TIMESTAMP(6),
  CONSTRAINT PK_TB_T24_MAIN_BORROWER_INFO PRIMARY KEY (APPLICATION_NO, RECID)
);
-- change-hint: active/exact; R6 checks CHECK_DATE against system calendar date before submit/authorize.

CREATE TABLE TB_T24_CO_BORROWER_INFO (
  APPLICATION_NO VARCHAR2(30 BYTE) NOT NULL,
  RECID VARCHAR2(10 BYTE) NOT NULL,
  DATA_SEQ NUMBER(2,0) NOT NULL,
  CHECK_DATE TIMESTAMP(6),
  CONSTRAINT PK_TB_T24_CO_BORROWER_INFO PRIMARY KEY (APPLICATION_NO, RECID, DATA_SEQ)
);
-- change-hint: active/exact; every required co-borrower CHECK_DATE must equal system calendar date.

CREATE TABLE TB_CLO_REASON (
  APPLICATION_NO VARCHAR2(30 BYTE) NOT NULL,
  REASON_CODE VARCHAR2(100 BYTE),
  CONSTRAINT PK_TB_CLO_REASON PRIMARY KEY (APPLICATION_NO)
);
-- change-hint: active/exact; non-success T24 result writes REASON_CODE=C10.

-- Referenced source tables for T24 generation and lookup:
-- TB_LOAN_CONDITION_DETAIL
-- TB_COLL_INFO
-- TB_COLL_INFO.SUG_VAL is an invalid-source comparison note only: db-diff TB_COLL_INFO has no SUG_VAL; T24 C12 source is TB_COLL_VALUE_INFO.SUG_VAL.
-- TB_MAIN_BORROWER_ACC (comparison-only: current backend branches G10/H8 on CURRENCY, but target contract uses TB_DISBUR_DATE.DISBURSEMENT_CURRENCY)
-- TB_BRANCH_PROFILE
--   PK columns: BRANCH_CODE, DEPT_CODE.
--   T24 source columns required by R7/TBD-0922-007:
--     T24_COMPANY is VARCHAR2(5 BYTE) by new DB reverify and feeds T24 B8/C9.
--     T24_BRANCH_CODE is VARCHAR2(20 BYTE) by DB reverify and feeds transaction branch.
--     T24_DEPT_CODE is VARCHAR2(5 BYTE) by DB reverify.
-- TB_PROCESS_CODE
