-- SRS schema snapshot for EPROC00120.
-- Evidence comes from docs/db-diff/02_tables/*.md and current source usage.
-- This file is not a migration script; it lists contract-relevant tables/columns.

CREATE TABLE TB_FINANCIAL_EVALUATION_FI (
    APPLICATION_NO VARCHAR2(30) NOT NULL,
    DATA_SEQ VARCHAR2(2) NOT NULL,
    NPL VARCHAR2(12),
    LLR VARCHAR2(12),
    LLR_OVER_NPL VARCHAR2(12),
    GGL VARCHAR2(12),
    AGREE_LARGE_EXPOSURE VARCHAR2(12),
    CREDIT_EXPOSURE_TO_SB VARCHAR2(12),
    RELATED_PARTY_EXPOSURE VARCHAR2(12),
    UNHEDGED_FOREIGN_CURR VARCHAR2(12),
    NET_INTEREST_MARGIN VARCHAR2(12),
    COST_INCOME VARCHAR2(12),
    ROA VARCHAR2(12),
    ROE VARCHAR2(12),
    LOANS_DEPOSITS VARCHAR2(12),
    LIQUIDITY_COVERAGE VARCHAR2(12),
    SOLVENCY VARCHAR2(12),
    TIER_ONE_CAPITAL VARCHAR2(12),
    RATIOS_DATE VARCHAR2(10),
    CONSTRAINT PK_TB_FINANCIAL_EVALUATION_FI PRIMARY KEY (APPLICATION_NO, DATA_SEQ)
);

CREATE TABLE TB_FIN_STATEMENT_BALANCE_FI (
    APPLICATION_NO VARCHAR2(30) NOT NULL,
    DATA_SEQ NUMBER(2) NOT NULL,
    BALANCE_DATE VARCHAR2(10),
    PERIODS VARCHAR2(3),
    TOTAL_ASSETS NUMBER(19,2),
    LOANS_DISCOUNTED NUMBER(17,2),
    DEPOSITS_FROM_CB_BF NUMBER(17,2),
    DEPOSITS_REMITTANCES NUMBER(17,2),
    TOTAL_STOCKHOLDER_EQUITY NUMBER(19,2),
    CONSTRAINT PK_TB_FIN_STATEMENT_BAL_FI PRIMARY KEY (APPLICATION_NO, DATA_SEQ)
);

CREATE TABLE TB_FIN_STATEMENT_INCOME_FI (
    APPLICATION_NO VARCHAR2(30) NOT NULL,
    DATA_SEQ NUMBER(2) NOT NULL,
    INCOME_DATE VARCHAR2(10),
    PERIODS VARCHAR2(3),
    OPERATING_EXPENSES NUMBER(17,2),
    CONTINUING_OP_INCOME_BT NUMBER(17,2),
    CONTINUING_OP_AT NUMBER(17,2),
    CONSTRAINT PK_TB_FIN_STATEMENT_INC_FI PRIMARY KEY (APPLICATION_NO, DATA_SEQ)
);

CREATE TABLE TB_LON_SUMMARY_INFO (
    APPLICATION_NO VARCHAR2(30) NOT NULL,
    LON_ATTRIBUTE VARCHAR2(2),
    SECURE_ATTRIBUTE VARCHAR2(2),
    APPLICATION_DATE VARCHAR2(10),
    BUSINESS_TYPE VARCHAR2(1),
    CONSTRAINT PK_TB_LON_SUMMARY_INFO PRIMARY KEY (APPLICATION_NO)
);

CREATE TABLE TB_MAIN_BORROWER_INFO_CORP (
    APPLICATION_NO VARCHAR2(30) NOT NULL,
    MAIN_BORROWER_NAME VARCHAR2(100),
    CONSTRAINT PK_TB_MAIN_BORROWER_INFO_CORP PRIMARY KEY (APPLICATION_NO)
);

CREATE TABLE TB_CHECK_POINTS_CS (
    APPLICATION_NO VARCHAR2(30) NOT NULL,
    EPROC00120 VARCHAR2(2) DEFAULT 'N',
    CONSTRAINT PK_TB_CHECK_POINTS_CS PRIMARY KEY (APPLICATION_NO)
);

CREATE TABLE TB_CHECK_POINTS_CU (
    APPLICATION_NO VARCHAR2(30) NOT NULL,
    EPROC00120 VARCHAR2(2) DEFAULT 'N',
    CONSTRAINT PK_TB_CHECK_POINTS_CU PRIMARY KEY (APPLICATION_NO)
);

CREATE TABLE TB_API_AUTH (
    API_ID VARCHAR2(100) NOT NULL,
    ROLE VARCHAR2(20) NOT NULL,
    REF_FUNCTION_ID VARCHAR2(20),
    CONSTRAINT PK_TB_API_AUTH PRIMARY KEY (API_ID, ROLE)
);

-- DB reconcile/delta notes:
-- 1. TB_FINANCIAL_EVALUATION_FI field list follows db-diff lines 38-56:
--    NPL, LLR, LLR_OVER_NPL, GGL, AGREE_LARGE_EXPOSURE,
--    CREDIT_EXPOSURE_TO_SB, RELATED_PARTY_EXPOSURE, UNHEDGED_FOREIGN_CURR,
--    NET_INTEREST_MARGIN, COST_INCOME, ROA, ROE, LOANS_DEPOSITS,
--    LIQUIDITY_COVERAGE, SOLVENCY, TIER_ONE_CAPITAL, RATIOS_DATE.
-- 2. Current backend DTO/entity additionally maps cetOneCapitalRatio and
--    totalCapitalRatio to CET_ONE_CAPITAL and TOTAL_CAPITAL. Those columns are
--    absent from the db-diff snapshot and PRD field mapping, so P-010 requires
--    RD/DBA to decide whether the snapshot is stale or implementation drift.
-- 3. Source statement tables contain numeric money values; target ratio table
--    stores calculated/display ratio values as VARCHAR2(12).
-- 4. Checkpoint writes use TB_CHECK_POINTS_CS or TB_CHECK_POINTS_CU by
--    corporate secured/unsecured branch.
