-- SRS EPROC00119 schema slice.
-- DB snapshot authority: docs/db-diff/02_tables.
-- TB_FIN_STATEMENT_CASHFLOW_FI markdown has malformed column_name cells; entity names are used below pending mother-folder recheck.
-- Mentioned auth/source tables: TB_LON_SUMMARY_INFO, TB_API_AUTH.

CREATE TABLE TB_FIN_STATEMENT_MAIN (
  APPLICATION_NO VARCHAR2(30) NOT NULL,
  CURRENCY VARCHAR2(3) NOT NULL,
  CCY_UNIT VARCHAR2(2),
  HIGHLIGHT LONG,
  COMPANY_NAME VARCHAR2(200),
  CRITERIA_1 VARCHAR2(1),
  CRITERIA_2 VARCHAR2(1),
  CRITERIA_3 VARCHAR2(1),
  DOES_NEED_AUDITED_FS VARCHAR2(1),
  HAVE_PROVIDED_AUDITED_FS VARCHAR2(1),
  AUDIT_FIRM VARCHAR2(50),
  OPINION_MEMO VARCHAR2(500),
  CONSTRAINT TB_FIN_STATEMENT_MAIN_PK PRIMARY KEY (APPLICATION_NO)
);

CREATE TABLE TB_FIN_STATEMENT_BALANCE_FI (
  APPLICATION_NO VARCHAR2(30) NOT NULL,
  DATA_SEQ NUMBER(2,0) NOT NULL,
  BALANCE_DATE VARCHAR2(10),
  PERIODS VARCHAR2(3),
  TOTAL_ASSETS NUMBER(19,2),
  TOTAL_LIAB_EQUITY NUMBER(19,2),
  DIFFERENCE NUMBER(17,2),
  CASH_AND_CASH_EQU NUMBER(17,2),
  DEPOSITS_PLACEMENT_WITH_CB_FIS NUMBER(17,2),
  FINANCIAL_ASSETS NUMBER(17,2),
  FINANCIAL_ASSETS_AT_FV NUMBER(17,2),
  SECURITIES_PURCHASED_URA NUMBER(17,2),
  AVAILALE_FOR_SFA NUMBER(17,2),
  HELD_TO_MATURITY_FA NUMBER(17,2),
  OTHER_FA NUMBER(17,2),
  RECEIVABLES NUMBER(17,2),
  ASSETS_CLASSIFIED_AS_HFS NUMBER(17,2),
  LOANS_DISCOUNTED NUMBER(17,2),
  BILLS_NEGOTIATED_ND NUMBER(17,2),
  OVERDRAFTS NUMBER(17,2),
  SHORT_TERM_LOANS NUMBER(17,2),
  ACCOUNTS_RECEIVABLE_FIN NUMBER(17,2),
  SECURED_OVERDRAFTS NUMBER(17,2),
  SHORT_TERM_SECURED_LOANS NUMBER(17,2),
  MARGIN_LOANS_RECEIVABLE NUMBER(17,2),
  MEDIUM_TERM_LOANS NUMBER(17,2),
  MEDIUM_TERM_SECURED_LOANS NUMBER(17,2),
  LONG_TERM_LOANS NUMBER(17,2),
  LONG_TERM_SECURED_LOANS NUMBER(17,2),
  OVERDUE_LOANS NUMBER(17,2),
  LESS_AFBDDAL NUMBER(17,2),
  PREMIUM_ADJ_ON_DISCOUNT_LOAN NUMBER(17,2),
  INVESTMENTS_ACCOUNT_FOR_UEM NUMBER(17,2),
  FIXED_ASSETS NUMBER(17,2),
  OTHER_ASSETS NUMBER(17,2),
  TOTAL_LIABILITIES NUMBER(19,2),
  TOTAL_STOCKHOLDER_EQUITY NUMBER(19,2),
  TYPE_OF_YEAR VARCHAR2(1),
  CONSTRAINT TB_FIN_STATEMENT_BALANCE_FI_PK PRIMARY KEY (APPLICATION_NO, DATA_SEQ)
);

CREATE TABLE TB_FIN_STATEMENT_INCOME_FI (
  APPLICATION_NO VARCHAR2(30) NOT NULL,
  DATA_SEQ NUMBER(2,0) NOT NULL,
  INCOME_DATE VARCHAR2(10),
  PERIODS VARCHAR2(3),
  NET_INTEREST_INCOME NUMBER(17,2),
  INTEREST_INCOME NUMBER(17,2),
  INTEREST_EXPENSES NUMBER(17,2),
  NET_OTH_NON_INTEREST_GAIN NUMBER(17,2),
  NET_FEE_COMMISSION_INCOME NUMBER(17,2),
  FIAN_ASSETS_BONDS_FVTPL NUMBER(17,2),
  AVAILABLE_SALE_FIN_ASSETS_RI NUMBER(17,2),
  HOLDING_MATURIRY_FIN_ASSETS_RI NUMBER(17,2),
  USER_EQUITY_METHOD NUMBER(17,2),
  EXCHANGE_GAIN NUMBER(17,2),
  IMPAIRMENT_LOSSES NUMBER(17,2),
  OTH_NET_GAIN NUMBER(17,2),
  NET_REVENUES NUMBER(17,2),
  ALLOWANCE_BAD_DEBT_LOAN NUMBER(17,2),
  OPERATING_EXPENSES NUMBER(17,2),
  DEPRECIATION_AMORTISATION NUMBER(17,2),
  CONTINUING_OP_INCOME_BT NUMBER(17,2),
  INCOME_TAX_EXPENSE NUMBER(17,2),
  CONTINUING_OP_AT NUMBER(17,2),
  DISCOUNTINUED_UNITS NUMBER(17,2),
  EXTRAORDINARY_GAIN NUMBER(17,2),
  CUMULATIVE_EFFECTS NUMBER(17,2),
  CONSOLIDATED_NET_INCOME_MERGE NUMBER(17,2),
  CONSOLIDATED_NET_INCOME NUMBER(17,2),
  NET_INCOME_MINORITY NUMBER(17,2),
  TYPE_OF_YEAR VARCHAR2(1),
  CONSTRAINT TB_FIN_STATEMENT_INCOME_FI_PK PRIMARY KEY (APPLICATION_NO, DATA_SEQ)
);

CREATE TABLE TB_FIN_STATEMENT_CASHFLOW_FI (
  APPLICATION_NO VARCHAR2(30) NOT NULL,
  DATA_SEQ NUMBER(2,0) NOT NULL,
  CASHFLOW_DATE VARCHAR2(10),
  PERIODS NUMBER(10,2),
  OPERATING_NET_CASHFLOW NUMBER(17,2),
  DEPRECIATION NUMBER(17,2),
  AMORTISATION NUMBER(17,2),
  INVESTING_NET_CASHFLOW NUMBER(17,2),
  FINANCING_NET_CASHFLOW NUMBER(17,2),
  NET_INCRE_DECRE_CASH NUMBER(17,2),
  OPENING_BALANCE NUMBER(17,2),
  END_BALANCE NUMBER(17,2),
  TYPE_OF_YEAR VARCHAR2(1),
  CONSTRAINT TB_FIN_STATEMENT_CASHFLOW_FI_PK PRIMARY KEY (APPLICATION_NO, DATA_SEQ)
);

CREATE TABLE TB_CHECK_POINTS_CS (
  APPLICATION_NO VARCHAR2(30) NOT NULL,
  EPROC00119 VARCHAR2(2) DEFAULT 'N',
  EPROC00120 VARCHAR2(2) DEFAULT 'N',
  CONSTRAINT TB_CHECK_POINTS_CS_EPROC00119_PK PRIMARY KEY (APPLICATION_NO)
);

CREATE TABLE TB_CHECK_POINTS_CU (
  APPLICATION_NO VARCHAR2(30) NOT NULL,
  EPROC00119 VARCHAR2(2) DEFAULT 'N',
  EPROC00120 VARCHAR2(2) DEFAULT 'N',
  CONSTRAINT TB_CHECK_POINTS_CU_EPROC00119_PK PRIMARY KEY (APPLICATION_NO)
);

-- TB_LON_SUMMARY_INFO supplies APPLICATION_NO, LON_ATTRIBUTE, SECURE_ATTRIBUTE, APPLICATION_DATE, CASE_PROGRESS.
-- TB_API_AUTH / TB_ROLE_TASK / service authorization proof remains pending RP51.

-- Delta tags:
-- DB-D1 (c + drift): TB_FIN_STATEMENT_MAIN follows active/exact snapshot PK APPLICATION_NO; current JPA/service identity also uses CURRENCY pending RP53.
-- DB-D2 (c): TB_FIN_STATEMENT_BALANCE_FI follows active/exact snapshot plus current entity; PK is APPLICATION_NO, DATA_SEQ.
-- DB-D3 (c): TB_FIN_STATEMENT_INCOME_FI follows active/exact snapshot, preserves typo physical names, and uses PK APPLICATION_NO, DATA_SEQ.
-- DB-D4 (pending): TB_FIN_STATEMENT_CASHFLOW_FI snapshot column_name extraction malformed; current entity names used pending mother-folder recheck.
-- DB-D5 (c + defect): TB_CHECK_POINTS_CS/CU use EPROC00119 and seed EPROC00120 on save; legacy 0119 checkpoint read defect used EPROI0_0119.
-- DB-D6 (pending): current entity/service use narrative split columns LOAN_REPAYMENT_1/2, FINANCIAL_SITUATION_1/2, BUSINESS_RISK_1/2, BORROWER_RISK_1/2, SUMMARY_1/2, but db-diff snapshot does not include them; reconcile under RP54.
