-- SRS EPROC00117 schema slice.
-- DB snapshot authority: docs/db-diff/02_tables.
-- Current implementation also maps TBFinancialEvaluationInfoEntity to TB_FINANCIAL_EVALUATION_INFO;
-- the active snapshot table for corporate business evaluation is TB_FINANCIAL_EVALUATION_INFO_CORP.
-- Mentioned source tables: TB_FIN_STATEMENT_BALANCE_GI, TB_FIN_STATEMENT_INCOME_GI, TB_FIN_STATEMENT_CASHFLOW_GI, TB_LON_SUMMARY_INFO.

CREATE TABLE TB_FINANCIAL_EVALUATION_GI (
  APPLICATION_NO VARCHAR2(30) NOT NULL,
  DATA_SEQ NUMBER(2,0) NOT NULL,
  CUR_RATIO VARCHAR2(12),
  QUICK_RATIO VARCHAR2(12),
  INTEREST_COVERAGE VARCHAR2(12),
  LEVERAGE VARCHAR2(12),
  DE_RATIO VARCHAR2(12),
  FIXED_RATIO VARCHAR2(12),
  FIXED_LT_RATIO VARCHAR2(12),
  OWN_CAPITAL_RATIO VARCHAR2(12),
  AR_TURNOVER VARCHAR2(12),
  DAYS_FOR_AR VARCHAR2(12),
  INVENTORY_TURNOVER VARCHAR2(12),
  NUM_OF_DAYS_FOR_INVENTORY VARCHAR2(12),
  AP_TURNOVER VARCHAR2(12),
  DAYS_FOR_AP VARCHAR2(12),
  CASH_CONVERSION_CYCLE VARCHAR2(12),
  TOTAL_ASSET_TURNOVER VARCHAR2(12),
  GROSS_PROFIT_MARGIN VARCHAR2(12),
  OP_PROFIT_MARGIN VARCHAR2(12),
  NET_PROFIT_MARGIN VARCHAR2(12),
  RETURN_ON_EQUITY VARCHAR2(12),
  RETURN_ON_ASSETS VARCHAR2(12),
  REVENUE_CREDIT_RATIO VARCHAR2(12),
  IN_OUT_RATIO VARCHAR2(12),
  CASH_FLOW_RATIO VARCHAR2(12),
  LT_INVEST_DIV_TOTAL_EQUITY VARCHAR2(12),
  LT_INVEST_DIV_TOTAL_ASSETS VARCHAR2(12),
  REVENUE_GROWTH VARCHAR2(12),
  NET_PROFIT_GROWTH VARCHAR2(12),
  AR_GROWTH VARCHAR2(12),
  BORROWING_GROWTH VARCHAR2(12),
  RATIOS_DATE VARCHAR2(10),
  CONSTRAINT TB_FINANCIAL_EVALUATION_GI_PK PRIMARY KEY (APPLICATION_NO, DATA_SEQ)
);

CREATE TABLE TB_FINANCIAL_EVALUATION_INFO_CORP (
  APPLICATION_NO VARCHAR2(30) NOT NULL,
  DATA_SEQ NUMBER(2,0) NOT NULL,
  EBIT_CURRENCY VARCHAR2(3),
  EBIT NUMBER(17,2),
  DEBT_PAYMENT_CURRENCY VARCHAR2(3),
  DEBT_PAYMENT NUMBER(17,2),
  EXISTING_PAYMENT_CURRENCY VARCHAR2(3),
  EXISTING_PAYMENT NUMBER(17,2),
  ESTIMATE_PAYMENT_CURRENCY VARCHAR2(3),
  ESTIMATE_PAYMENT NUMBER(17,2),
  OTHER_DEBT_PAYMENT_CURRENCY VARCHAR2(3),
  OTHER_DEBT_PAYMENT NUMBER(17,2),
  DSR_CURRENCY VARCHAR2(3),
  DSR NUMBER(17,2),
  CONSTRAINT TB_FINANCIAL_EVALUATION_INFO_CORP_PK PRIMARY KEY (APPLICATION_NO, DATA_SEQ)
);

-- Current code alias conflict pending RP35:
-- TB_FINANCIAL_EVALUATION_INFO is referenced by TBFinancialEvaluationInfoEntity and must be reconciled with TB_FINANCIAL_EVALUATION_INFO_CORP.

CREATE TABLE TB_CHECK_POINTS_CS (
  APPLICATION_NO VARCHAR2(30) NOT NULL,
  EPROC00117 VARCHAR2(2) DEFAULT 'N',
  CONSTRAINT TB_CHECK_POINTS_CS_EPROC00117_PK PRIMARY KEY (APPLICATION_NO)
);

CREATE TABLE TB_CHECK_POINTS_CU (
  APPLICATION_NO VARCHAR2(30) NOT NULL,
  EPROC00117 VARCHAR2(2) DEFAULT 'N',
  CONSTRAINT TB_CHECK_POINTS_CU_EPROC00117_PK PRIMARY KEY (APPLICATION_NO)
);

-- Source/read tables for computed GI ratios, schema owned by EPROC00116:
-- TB_FIN_STATEMENT_BALANCE_GI: APPLICATION_NO, DATA_SEQ, BALANCE_DATE, PERIODS, TOTAL_ASSETS, TOTAL_LIAB_EQUITY, DIFFERENCE, ...
-- TB_FIN_STATEMENT_INCOME_GI: APPLICATION_NO, DATA_SEQ, IMCOME_DATE, PERIODS, REVENUES, COST_OF_GOOD_SOLD, CUR_PERIOD_PROFIT, ...
-- TB_FIN_STATEMENT_CASHFLOW_GI: APPLICATION_NO, DATA_SEQ, CASHFLOW_DATE, PERIOD, OPERATING_NET_CASHFLOW, END_BALANCE, ...
-- TB_LON_SUMMARY_INFO: APPLICATION_NO, LON_ATTRIBUTE, SECURE_ATTRIBUTE, APPLICATION_DATE, ...

-- Delta tags:
-- DB-D1 (c): TB_FINANCIAL_EVALUATION_GI follows active/exact snapshot.
-- DB-D2 (pending): TB_FINANCIAL_EVALUATION_INFO_CORP vs current TB_FINANCIAL_EVALUATION_INFO alias requires DBA/RD confirmation.
-- DB-D3 (c): checkpoint columns are new EPROC00117 columns in TB_CHECK_POINTS_CS/CU.
