-- SRS schema excerpt for EPROZ00100 To Do List.
-- Source: docs/db-diff/02_tables/*.md as local new DB snapshot.
-- Change hints:
-- DB-D1 carried: TB_LON_SUMMARY_INFO active/exact, copied with modified column data.
-- DB-D2 carried + @PENDING: TB_APP_HISTORY active/exact; PRD/legacy proxy agent fields need DBA/RD reconciliation.
-- DB-D3 carried: TB_DEL_REASON and TB_CLO_REASON active/exact.
-- DB-D4 carried: TB_RELATED_PARTY_INFO, TB_LOAN_CONDITION_DETAIL, TB_EMP_PROXY active/exact read dependencies.
-- DB-D5 changed: TB_ROLE_DEFINE, TB_PROCESS_CODE, TB_API_AUTH active/exact but rewritten seed/config.
-- REF-D1 changed: latest refactor baseline exposes epl-list-todolist, epl-case-insert-delreason, epl-case-insert-cloreason.
-- REF-D5 @PENDING: prompt/session/download/reason-list endpoint ownership is draft until RD confirms artifacts.
-- External source-only tables mentioned by refactor evidence: TB_MAIN_BORROWER_PERSONAL_INFO, TB_MAIN_BORROWER_INFO_CORP.

CREATE TABLE TB_LON_SUMMARY_INFO (
  APPLICATION_NO VARCHAR2(30 BYTE) NOT NULL,
  LON_TYPE_CODE VARCHAR2(5 BYTE),
  PRODUCT_CODE VARCHAR2(5 BYTE),
  APPLICATION_DATE TIMESTAMP(6),
  RECEIVED_DATE TIMESTAMP(6),
  DISTRIBUTION_DATE TIMESTAMP(6),
  DECISION_DATE TIMESTAMP(6),
  CASE_PROGRESS VARCHAR2(5 BYTE),
  LON_ATTRIBUTE VARCHAR2(2 BYTE),
  SECURE_ATTRIBUTE VARCHAR2(2 BYTE),
  CR_CODE VARCHAR2(7 BYTE),
  CURRENT_USER_ID VARCHAR2(7 BYTE),
  CA_CODE VARCHAR2(5 BYTE),
  RE_DISTRIBUTION VARCHAR2(1 BYTE) DEFAULT 'N',
  IS_AUTODIS VARCHAR2(2 BYTE),
  CONSTRAINT PK_TB_LON_SUMMARY_INFO PRIMARY KEY (APPLICATION_NO)
);

CREATE TABLE TB_APP_HISTORY (
  APPLICATION_NO VARCHAR2(30 BYTE) NOT NULL,
  APP_PROCESS_CODE VARCHAR2(5 BYTE) NOT NULL,
  PROCESS_EMP_CODE VARCHAR2(7 BYTE),
  PROCESS_EMP_NAME VARCHAR2(50 BYTE),
  PROCESS_BRANCH_CODE VARCHAR2(5 BYTE),
  PROCESS_BRANCH_NAME VARCHAR2(50 BYTE),
  -- PENDING-Z010: legacy writes PROCESS_AGENT_CODE/PROCESS_AGENT_NAME for proxy delete/close,
  -- but local db-diff TB_APP_HISTORY snapshot lists only seven physical columns.
  PROCESS_DATE TIMESTAMP(6) NOT NULL,
  CONSTRAINT PK_TB_APP_HISTORY PRIMARY KEY (APPLICATION_NO, APP_PROCESS_CODE, PROCESS_DATE)
);

CREATE TABLE TB_DEL_REASON (
  APPLICATION_NO VARCHAR2(30 BYTE) NOT NULL,
  REASON_CODE VARCHAR2(100 BYTE),
  OTH_REASON VARCHAR2(100 BYTE),
  DEL_DATE TIMESTAMP(6),
  CONSTRAINT PK_TB_DEL_REASON PRIMARY KEY (APPLICATION_NO)
);

CREATE TABLE TB_CLO_REASON (
  APPLICATION_NO VARCHAR2(30 BYTE) NOT NULL,
  REASON_CODE VARCHAR2(100 BYTE),
  OTH_REASON VARCHAR2(100 BYTE),
  CLOSE_DATE TIMESTAMP(6),
  CONSTRAINT PK_TB_CLO_REASON PRIMARY KEY (APPLICATION_NO)
);

CREATE TABLE TB_RELATED_PARTY_INFO (
  APPLICATION_NO VARCHAR2(30 BYTE) NOT NULL,
  BORROWER_NAME VARCHAR2(50 BYTE) NOT NULL,
  IS_MAIN_BORR VARCHAR2(1 BYTE),
  IS_CUB_RELATED VARCHAR2(1 BYTE),
  IS_CUBC_RELATED VARCHAR2(1 BYTE),
  DATA_SEQ NUMBER(2,0) NOT NULL,
  CONSTRAINT PK_TB_RELATED_PARTY_INFO PRIMARY KEY (APPLICATION_NO, BORROWER_NAME, DATA_SEQ)
);

CREATE TABLE TB_LOAN_CONDITION_DETAIL (
  APPLICATION_NO VARCHAR2(30 BYTE) NOT NULL,
  CON_TYPE VARCHAR2(5 BYTE) NOT NULL,
  SEQNO NUMBER(3,0) NOT NULL,
  LOAN_PURPOSE VARCHAR2(2 BYTE),
  LOAN_AMOUNT_CURRENCY VARCHAR2(3 BYTE),
  LOAN_AMOUNT NUMBER(17,2),
  LOAN_TYPE VARCHAR2(2 BYTE),
  CONSTRAINT PK_TB_LOAN_CONDITION_DETAIL PRIMARY KEY (APPLICATION_NO, CON_TYPE, SEQNO)
);

CREATE TABLE TB_EMP_PROXY (
  EMP_ID VARCHAR2(10 BYTE) NOT NULL,
  PROXY_ID VARCHAR2(10 BYTE),
  STR_TIME TIMESTAMP(6) NOT NULL,
  END_TIME TIMESTAMP(6),
  UPDATE_EMP_ID VARCHAR2(10 BYTE),
  UPDATE_DATE TIMESTAMP(6),
  CONSTRAINT PK_TB_EMP_PROXY PRIMARY KEY (EMP_ID)
);

CREATE TABLE TB_ROLE_DEFINE (
  ROLE_ID VARCHAR2(3 BYTE) NOT NULL,
  ROLE_NAME VARCHAR2(50 BYTE),
  ROLE_DESC VARCHAR2(50 BYTE),
  CONSTRAINT PK_TB_ROLE_DEFINE PRIMARY KEY (ROLE_ID)
);

CREATE TABLE TB_PROCESS_CODE (
  APP_PROCESS_CODE VARCHAR2(5 BYTE) NOT NULL,
  APP_PROCESS_NAME VARCHAR2(200 BYTE),
  PROCESS_DESC VARCHAR2(300 BYTE),
  IS_SHOW VARCHAR2(1 BYTE),
  PROCESS_TYPE VARCHAR2(2 BYTE),
  CONSTRAINT PK_TB_PROCESS_CODE PRIMARY KEY (APP_PROCESS_CODE)
);

CREATE TABLE TB_API_AUTH (
  API_ID VARCHAR2(100 BYTE) NOT NULL,
  ROLE VARCHAR2(100 BYTE) NOT NULL,
  REF_FUNCTION_ID VARCHAR2(100 BYTE),
  UPDATE_USER VARCHAR2(10 BYTE),
  CONSTRAINT PK_TB_API_AUTH PRIMARY KEY (API_ID)
);
