-- SRS schema contract for EPROC00112 CBC Banking Relationship.
-- Sources: db-diff tables under docs/db-diff/02_tables and SRS reconcile notes in spec.md.
-- Source-only tables referenced by SRS R2/R3: TB_MAIN_BORROWER_INFO_CORP, TB_CO_BORROWER_INFO_CORP,
-- TB_GUARANTOR_INFO, and TB_GUARANTOR_INFO_CORP remain source tables and are not owned by this page schema.
-- Legacy checkpoint tables referenced by reconcile: TB_CHECK_POINT_CORP, TB_CHECK_POINT_CU,
-- TB_CHECK_POINT_RC_CORP, and TB_CHECK_POINT_RC_CU are removed_or_unused/transferred in db-diff.

-- Source attributes used for CS/CU branch; evidence docs/db-diff/02_tables/TB_LON_SUMMARY_INFO.md:38-88.
-- Latest schema reverify adds PROJECT_CODE at C:/Users/00596357/Documents/project/kh/epro/epro-db/out/legacy_schema_reverify_new02_columns.tsv:1849.
CREATE TABLE TB_LON_SUMMARY_INFO (
  APPLICATION_NO VARCHAR2(30) NOT NULL,
  LON_TYPE_CODE VARCHAR2(5),
  PRODUCT_CODE VARCHAR2(5),
  LON_APP_CURRENCY VARCHAR2(3),
  LON_APP_AMT NUMBER(17,2),
  OWNER_FUND NUMBER(17,2),
  GET_APPNO_DATE VARCHAR2(6),
  APPLICATION_DATE TIMESTAMP(6),
  RECEIVED_DATE TIMESTAMP(6),
  DISTRIBUTION_DATE TIMESTAMP(6),
  DECISION_DATE TIMESTAMP(6),
  CASE_PROGRESS VARCHAR2(5),
  LON_ATTRIBUTE VARCHAR2(2),
  SECURE_ATTRIBUTE VARCHAR2(2),
  BRANCH_CODE VARCHAR2(10),
  AO_ASSISTANT_CODE VARCHAR2(7),
  AO_CODE VARCHAR2(7),
  DEP_CODE VARCHAR2(5),
  REF_APPLICATION_NO VARCHAR2(30),
  AO_PROPOS_APPR_LEVEL VARCHAR2(2),
  ASSESSMENT_TYPE VARCHAR2(1),
  BUSINESS_TYPE VARCHAR2(1),
  CR_CODE VARCHAR2(7),
  CA_RELATED_PARTY_COMPLETED VARCHAR2(1),
  CURRENT_USER_ID VARCHAR2(7),
  IS_LLC VARCHAR2(1),
  IS_LC VARCHAR2(1),
  MANAGER_CODE VARCHAR2(7),
  CR_RELATED_PARTY_COMPLETED VARCHAR2(1),
  CR_SCORE_CARD_COMPLETED VARCHAR2(2),
  FIN_APPR_LEVEL VARCHAR2(2),
  CA_CODE VARCHAR2(5),
  SYS_APPR_LEVEL VARCHAR2(4),
  CR_APPR_LEVEL VARCHAR2(4),
  ACCOUNT_OFFICE_ID VARCHAR2(7),
  RE_DISTRIBUTION VARCHAR2(1) DEFAULT 'N',
  HOUSING_PROJECT_CODE VARCHAR2(10),
  IS_EXISTING_CONSTRUCTION_LOAN VARCHAR2(1),
  DOC_CHECKLIST_COMPLETED VARCHAR2(1),
  MTG_PRODUCT_CODE VARCHAR2(5),
  REFIANANCE_CASE VARCHAR2(1),
  SYSTEM_VER VARCHAR2(5),
  APP_CON_TYPE VARCHAR2(5),
  FIN_CON_TYPE VARCHAR2(5),
  CADM_CODE VARCHAR2(7),
  CADC_CODE VARCHAR2(7),
  IS_AUTODIS VARCHAR2(2),
  DISBURSING_DATE TIMESTAMP(6),
  IS_CONTR VARCHAR2(2),
  CGCC_GUARANTEE VARCHAR2(1),
  BELONG_DEP_CODE VARCHAR2(5),
  PROJECT_CODE VARCHAR2(5),
  CONSTRAINT PK_TB_LON_SUMMARY_INFO PRIMARY KEY (APPLICATION_NO)
);

-- TB_CBC_* tables follow latest schema reverify for lengths and PKs; current db-diff markdown has stale
-- borrower/guarantor name, late-payment, note length, and BGL_INFO PK details.
-- Evidence: C:/Users/00596357/Documents/project/kh/epro/epro-db/out/legacy_schema_reverify_new02_columns.tsv:44-119
-- and C:/Users/00596357/Documents/project/kh/epro/epro-db/out/legacy_schema_reverify_new02_pk.tsv:12-34.
CREATE TABLE TB_CBC_BBL (
  APPLICATION_NO VARCHAR2(30) NOT NULL,
  BORROWER_NAME VARCHAR2(100) NOT NULL,
  SEQ_NO NUMBER(5) NOT NULL,
  IS_MAIN_BORR VARCHAR2(1),
  IS_REPORT_AVAILABLE VARCHAR2(1),
  ALL_LOANS_STATUS VARCHAR2(1),
  IS_ANY_LATE_PAYMENT VARCHAR2(1),
  LATE_PAYMENT_MONTH_YEAR VARCHAR2(7),
  AS_OF_DATE DATE,
  NOTE VARCHAR2(1000),
  CONSTRAINT PK_TB_CBC_BBL PRIMARY KEY (APPLICATION_NO, BORROWER_NAME, SEQ_NO)
);

-- TB_CBC_BBL_INFO is active/exact; columns and PK are documented at docs/db-diff/02_tables/TB_CBC_BBL_INFO.md:32-52.
CREATE TABLE TB_CBC_BBL_INFO (
  APPLICATION_NO VARCHAR2(30) NOT NULL,
  BORROWER_NAME VARCHAR2(100) NOT NULL,
  SEQ_NO NUMBER(5) NOT NULL,
  INFO_SEQ_NO NUMBER(5) NOT NULL,
  BANKER_NAME VARCHAR2(20),
  CREDIT_AMOUNT_CURRENCY VARCHAR2(3),
  CREDIT_AMOUNT NUMBER(17,2),
  OUTSTANDING_BALANCE_CURRENCY VARCHAR2(3),
  OUTSTANDING_BALANCE NUMBER(17,2),
  TENOR VARCHAR2(20),
  STATUS_CODE VARCHAR2(1),
  MATURITY_DATE DATE,
  PRODUCT_CODE VARCHAR2(3),
  SECURITY_CODE VARCHAR2(2),
  REPAY_RECORDS VARCHAR2(1),
  CONSTRAINT PK_TB_CBC_BBL_INFO PRIMARY KEY (APPLICATION_NO, BORROWER_NAME, SEQ_NO, INFO_SEQ_NO)
);

-- TB_CBC_BGL is active/exact; columns and PK are documented at docs/db-diff/02_tables/TB_CBC_BGL.md:32-47.
CREATE TABLE TB_CBC_BGL (
  APPLICATION_NO VARCHAR2(30) NOT NULL,
  BORROWER_NAME VARCHAR2(100) NOT NULL,
  SEQ_NO NUMBER(5) NOT NULL,
  IS_MAIN_BORR VARCHAR2(1),
  IS_REPORT_AVAILABLE VARCHAR2(1),
  ALL_LOANS_STATUS VARCHAR2(1),
  IS_ANY_LATE_PAYMENT VARCHAR2(1),
  LATE_PAYMENT_MONTH_YEAR VARCHAR2(7),
  AS_OF_DATE DATE,
  NOTE VARCHAR2(1000),
  CONSTRAINT PK_TB_CBC_BGL PRIMARY KEY (APPLICATION_NO, BORROWER_NAME, SEQ_NO)
);

-- TB_CBC_BGL_INFO is active/exact; latest schema reverify PK is APPLICATION_NO, BORROWER_NAME, SEQ_NO, INFO_SEQ_NO.
CREATE TABLE TB_CBC_BGL_INFO (
  APPLICATION_NO VARCHAR2(30) NOT NULL,
  BORROWER_NAME VARCHAR2(100) NOT NULL,
  SEQ_NO NUMBER(5) NOT NULL,
  INFO_SEQ_NO NUMBER(5) NOT NULL,
  BANKER_NAME VARCHAR2(20),
  CREDIT_AMOUNT_CURRENCY VARCHAR2(3),
  CREDIT_AMOUNT NUMBER(17,2),
  OUTSTANDING_BALANCE_CURRENCY VARCHAR2(3),
  OUTSTANDING_BALANCE NUMBER(17,2),
  TENOR VARCHAR2(20),
  STATUS_CODE VARCHAR2(1),
  MATURITY_DATE DATE,
  PRODUCT_CODE VARCHAR2(3),
  SECURITY_CODE VARCHAR2(2),
  REPAY_RECORDS VARCHAR2(1),
  CONSTRAINT PK_TB_CBC_BGL_INFO PRIMARY KEY (APPLICATION_NO, BORROWER_NAME, SEQ_NO, INFO_SEQ_NO)
);

-- TB_CBC_GBGL is active/exact; columns and PK are documented at docs/db-diff/02_tables/TB_CBC_GBGL.md:32-47.
CREATE TABLE TB_CBC_GBGL (
  APPLICATION_NO VARCHAR2(30) NOT NULL,
  GUARANTOR_NAME VARCHAR2(100) NOT NULL,
  IS_IND VARCHAR2(1) NOT NULL,
  SEQ_NO NUMBER(5) NOT NULL,
  IS_REPORT_AVAILABLE VARCHAR2(1),
  ALL_LOANS_STATUS VARCHAR2(1),
  IS_ANY_LATE_PAYMENT VARCHAR2(1),
  LATE_PAYMENT_MONTH_YEAR VARCHAR2(7),
  AS_OF_DATE DATE,
  NOTE VARCHAR2(1000),
  CONSTRAINT PK_TB_CBC_GBGL PRIMARY KEY (APPLICATION_NO, GUARANTOR_NAME, IS_IND, SEQ_NO)
);

-- TB_CBC_GBGL_INFO is active/exact; columns and PK are documented at docs/db-diff/02_tables/TB_CBC_GBGL_INFO.md:32-53.
CREATE TABLE TB_CBC_GBGL_INFO (
  APPLICATION_NO VARCHAR2(30) NOT NULL,
  BORROWER_NAME VARCHAR2(100) NOT NULL,
  IS_IND VARCHAR2(1) NOT NULL,
  SEQ_NO NUMBER(5) NOT NULL,
  INFO_SEQ_NO NUMBER(5) NOT NULL,
  BANKER_NAME VARCHAR2(20),
  CREDIT_AMOUNT_CURRENCY VARCHAR2(3),
  CREDIT_AMOUNT NUMBER(17,2),
  OUTSTANDING_BALANCE_CURRENCY VARCHAR2(3),
  OUTSTANDING_BALANCE NUMBER(17,2),
  TENOR VARCHAR2(20),
  STATUS_CODE VARCHAR2(1),
  MATURITY_DATE DATE,
  PRODUCT_CODE VARCHAR2(3),
  SECURITY_CODE VARCHAR2(2),
  REPAY_RECORDS VARCHAR2(1),
  CONSTRAINT PK_TB_CBC_GBGL_INFO PRIMARY KEY (APPLICATION_NO, BORROWER_NAME, SEQ_NO, IS_IND, INFO_SEQ_NO)
);

-- New checkpoint tables are active/exact and replace legacy TB_CHECK_POINT_* tables for EPROC00112.
-- Evidence: docs/db-diff/02_tables/TB_CHECK_POINTS_CS.md:38-53 and docs/db-diff/02_tables/TB_CHECK_POINTS_CU.md:38-50.
-- TB_CHECK_POINTS_CS.EPROCSU0140 has a blank data_type in db-diff markdown at line 43; schema reverify
-- recovers VARCHAR2 length 2 at C:/Users/00596357/Documents/project/kh/epro/epro-db/out/legacy_schema_reverify_new02_columns.tsv:135.
-- Latest schema reverify extends CS to EPROCSU0171 at line 136 and CU to EPROC00114/EPROCSU0140
-- at lines 149 and 151; these columns are absent from the current db-diff markdown.
CREATE TABLE TB_CHECK_POINTS_CS (
  APPLICATION_NO VARCHAR2(30) NOT NULL,
  EPROZ00800 VARCHAR2(2) DEFAULT 'N',
  EPROCSU0110 VARCHAR2(2) DEFAULT 'N',
  EPROCSU0120 VARCHAR2(2) DEFAULT 'N',
  EPROCSU0130 VARCHAR2(2) DEFAULT 'N',
  EPROCSU0150 VARCHAR2(2) DEFAULT 'N',
  EPROC00115 VARCHAR2(2) DEFAULT 'N',
  EPROC00112 VARCHAR2(2) DEFAULT 'N',
  EPROC00116 VARCHAR2(2) DEFAULT 'N',
  EPROC00119 VARCHAR2(2) DEFAULT 'N',
  EPROC00117 VARCHAR2(2) DEFAULT 'N',
  EPROC00120 VARCHAR2(2) DEFAULT 'N',
  EPROC00118 VARCHAR2(2) DEFAULT 'N',
  EPROC00114 VARCHAR2(2) DEFAULT 'N',
  EPROCSU0160 VARCHAR2(2) DEFAULT 'N',
  EPROCSU0140 VARCHAR2(2) DEFAULT 'N',
  EPROCSU0171 VARCHAR2(2) DEFAULT 'N',
  CONSTRAINT PK_TB_CHECK_POINTS_CS PRIMARY KEY (APPLICATION_NO)
);

CREATE TABLE TB_CHECK_POINTS_CU (
  APPLICATION_NO VARCHAR2(30) NOT NULL,
  EPROZ00800 VARCHAR2(2) DEFAULT 'N',
  EPROCSU0110 VARCHAR2(2) DEFAULT 'N',
  EPROCSU0120 VARCHAR2(2) DEFAULT 'N',
  EPROCSU0130 VARCHAR2(2) DEFAULT 'N',
  EPROC00115 VARCHAR2(2) DEFAULT 'N',
  EPROC00112 VARCHAR2(2) DEFAULT 'N',
  EPROC00116 VARCHAR2(2) DEFAULT 'N',
  EPROC00119 VARCHAR2(2) DEFAULT 'N',
  EPROC00117 VARCHAR2(2) DEFAULT 'N',
  EPROC00120 VARCHAR2(2) DEFAULT 'N',
  EPROC00118 VARCHAR2(2) DEFAULT 'N',
  EPROC00114 VARCHAR2(2) DEFAULT 'N',
  EPROCSU0160 VARCHAR2(2) DEFAULT 'N',
  EPROCSU0140 VARCHAR2(2) DEFAULT 'N',
  CONSTRAINT PK_TB_CHECK_POINTS_CU PRIMARY KEY (APPLICATION_NO)
);

-- Source-only borrower tables used to populate BBL/BGL; DDL is outside this
-- CBC persistence bundle but table presence is required for traceability.
-- Evidence: docs/db-diff/02_tables/TB_MAIN_BORROWER_INFO_CORP.md and
-- docs/db-diff/02_tables/TB_CO_BORROWER_INFO_CORP.md.
-- TB_MAIN_BORROWER_INFO_CORP.
-- TB_CO_BORROWER_INFO_CORP.

-- Legacy checkpoint tables referenced for parity/reconcile only. New writes
-- target TB_CHECK_POINTS_CS/TB_CHECK_POINTS_CU above.
-- Evidence: docs/db-diff/02_tables/TB_CHECK_POINT_CORP.md:13-16,
-- docs/db-diff/02_tables/TB_CHECK_POINT_CU.md:13-16,
-- docs/db-diff/02_tables/TB_CHECK_POINT_RC_CORP.md:13-16,
-- docs/db-diff/02_tables/TB_CHECK_POINT_RC_CU.md:13-16.
-- TB_CHECK_POINT_CORP.
-- TB_CHECK_POINT_CU.
-- TB_CHECK_POINT_RC_CORP.
-- TB_CHECK_POINT_RC_CU.

-- Authorization seed table referenced by R9; not sufficient without service-level
-- edit/query/old-case checks.
-- Evidence: docs/db-diff/02_tables/TB_API_AUTH.md.
-- TB_API_AUTH.
