-- SRS schema excerpt for EPROZ00800 Revised Item.
-- Source: docs/db-diff/02_tables/*.md as local new DB snapshot.
-- Change hints:
-- DB-D1 carried+constrained: TB_REVISED_ITEM active/exact; physical REASON_MEMO is VARCHAR2(4000), execute input max remains 3000.
-- DB-D2 carried: TB_REVISED_ITEM_DETAIL active/exact for original loan condition restore.
-- DB-D3 carried: TB_LON_SUMMARY_INFO is authoritative for loan/case attributes and REF_APPLICATION_NO.
-- BP2 case-type mapping: LON_TYPE_CODE uses TB_LON_TYPE semantics (01 New, 02 Additional, 03 Renew,
-- 04 Change Condition, 05 Restructure when present). EPROZ00800 supports only 03/04.
-- DB-D4 changed: old TB_CHECK_POINT_RC* tables are removed_or_unused; use TB_CHECK_POINTS_IS/IU/CS/CU.
-- BP4: EPROZ00800 may mark 0150 only where a physical checkpoint key exists (IS/CS). 0173 summary pages are not checkpoint keys in this bundle.
-- DB-D5 carried: TB_COMMON_FIELD_OPTIONS and TB_MULTI_LANG provide REVISED_ITEM display names; no code-table maintenance in this page.
-- DB-D6 carried: downstream side-effect tables are dependencies, not owned by this bundle.
-- DB-D7 verified: SELECT-only closeout found both final TB_API_AUTH query/save rows with REF_FUNCTION_ID=EPROZ00800.
-- R7/R16 blocker remains outside TB_API_AUTH: TB_PAGE_COLUMN_AUTH_DETAIL currently lacks reason.item and needs DBA/RD backfill or equivalent fix.
-- External dependency tables referenced for side effects and verification: TB_MAIN_BORROWER_PERSONAL_INFO, TB_MAIN_BORROWER_INFO_CORP,
-- TB_GUARANTOR_INFO, TB_GUARANTOR_INFO_CORP, TB_COLL_INFO, TB_COLL_VALUE_INFO, TB_COLL_LTV, TB_COLL_PROVIDER_INFO,
-- TB_COLL_TITLE_DETAIL, TB_COLL_VALUE_DETAIL, TB_COLL_TITLE_REGIS_OWNER, TB_COLL_SITE_VISIT, TB_INSPE_AO,
-- TB_CROSS_CHARGE_DETAIL, TB_LOAN_CONDITION_FEE.
-- Removed/unused legacy checkpoint references: TB_CHECK_POINT_RC, TB_CHECK_POINT_RC_IU, TB_CHECK_POINT_RC_CORP, TB_CHECK_POINT_RC_CU.

CREATE TABLE TB_REVISED_ITEM (
  APPLICATION_NO VARCHAR2(30 BYTE),
  REASON_MEMO VARCHAR2(4000 BYTE),
  UPD_DATE DATE,
  ITEM1 VARCHAR2(1 BYTE),
  ITEM2 VARCHAR2(1 BYTE),
  ITEM3 VARCHAR2(1 BYTE),
  ITEM4 VARCHAR2(1 BYTE),
  ITEM5 VARCHAR2(1 BYTE),
  ITEM6 VARCHAR2(1 BYTE),
  ITEM7 VARCHAR2(1 BYTE),
  ITEM8 VARCHAR2(1 BYTE),
  ITEM9 VARCHAR2(1 BYTE),
  ITEM10 VARCHAR2(1 BYTE),
  ITEM11 VARCHAR2(1 BYTE),
  ITEM12 VARCHAR2(1 BYTE),
  ITEM13 VARCHAR2(1 BYTE),
  ITEM14 VARCHAR2(1 BYTE),
  CONSTRAINT PK_TB_REVISED_ITEM PRIMARY KEY (APPLICATION_NO)
);

CREATE TABLE TB_REVISED_ITEM_DETAIL (
  APPLICATION_NO VARCHAR2(30 BYTE) NOT NULL,
  ITEM1 VARCHAR2(1 BYTE),
  ITEM2 VARCHAR2(1 BYTE),
  ITEM3 VARCHAR2(1 BYTE),
  ITEM4 VARCHAR2(1 BYTE),
  ITEM5 VARCHAR2(1 BYTE),
  ITEM6 VARCHAR2(1 BYTE),
  ITEM7 VARCHAR2(1 BYTE),
  ITEM8 VARCHAR2(1 BYTE),
  ITEM9 VARCHAR2(1 BYTE),
  ITEM10 VARCHAR2(1 BYTE),
  ITEM11 VARCHAR2(1 BYTE),
  ITEM12 VARCHAR2(1 BYTE),
  ITEM13 VARCHAR2(1 BYTE),
  ITEM14 VARCHAR2(1 BYTE),
  ORI_APPLICATION_NO VARCHAR2(30 BYTE) NOT NULL,
  ORI_CON_TYPE VARCHAR2(5 BYTE),
  ORI_SEQNO NUMBER(3,0)
);

CREATE TABLE TB_LON_SUMMARY_INFO (
  APPLICATION_NO VARCHAR2(30 BYTE) NOT NULL,
  -- Case-type axis, distinct from LON_ATTRIBUTE/SECURE_ATTRIBUTE page/checkpoint family.
  LON_TYPE_CODE VARCHAR2(5 BYTE),
  LON_ATTRIBUTE VARCHAR2(2 BYTE),
  SECURE_ATTRIBUTE VARCHAR2(2 BYTE),
  REF_APPLICATION_NO VARCHAR2(30 BYTE),
  CONSTRAINT PK_TB_LON_SUMMARY_INFO PRIMARY KEY (APPLICATION_NO)
);

CREATE TABLE TB_COMMON_FIELD_OPTIONS (
  SYS_CODE VARCHAR2(10 BYTE) NOT NULL,
  MSG_CODE VARCHAR2(30 BYTE) NOT NULL,
  MSG_OPTION VARCHAR2(50 BYTE) NOT NULL,
  MSG_SER_NO NUMBER(4,0) NOT NULL,
  LANG_KEY VARCHAR2(50 BYTE) NOT NULL,
  UPD_EMP_NO VARCHAR2(10 BYTE) NOT NULL,
  UPD_EMP_ID VARCHAR2(10 BYTE) NOT NULL,
  UPD_EMP_NAME NVARCHAR2(20),
  UPD_DATE DATE NOT NULL,
  IS_SHOW VARCHAR2(1 BYTE) DEFAULT 'Y' NOT NULL,
  MSG_VER VARCHAR2(5 BYTE) NOT NULL,
  CONSTRAINT PK_TB_COMMON_FIELD_OPTIONS PRIMARY KEY (SYS_CODE, MSG_CODE, MSG_OPTION, LANG_KEY, MSG_VER)
);

CREATE TABLE TB_MULTI_LANG (
  LANG_KEY VARCHAR2(50 BYTE) NOT NULL,
  LANG_TYPE VARCHAR2(10 BYTE) NOT NULL,
  LANG_NAME NVARCHAR2(200),
  MEMO NVARCHAR2(50),
  UPDATE_USER_NM VARCHAR2(50 BYTE),
  UPDATE_DATE TIMESTAMP(6),
  UPDATE_USER_ID VARCHAR2(10 BYTE),
  CONSTRAINT PK_TB_MULTI_LANG PRIMARY KEY (LANG_KEY, LANG_TYPE)
);

CREATE TABLE TB_CHECK_POINTS_IS (
  APPLICATION_NO VARCHAR2(30 BYTE) NOT NULL,
  EPROZ00800 VARCHAR2(2 BYTE) DEFAULT 'N',
  EPROISU0110 VARCHAR2(2 BYTE) DEFAULT 'N',
  EPROISU0120 VARCHAR2(2 BYTE) DEFAULT 'N',
  EPROISU0130 VARCHAR2(2 BYTE) DEFAULT 'N',
  EPROISU0140 VARCHAR2(2 BYTE) DEFAULT 'N',
  -- BP4: physical downstream 0150 key exists for IS.
  EPROISU0150 VARCHAR2(2 BYTE) DEFAULT 'N',
  EPROISU0160 VARCHAR2(2 BYTE) DEFAULT 'N',
  CONSTRAINT PK_TB_CHECK_POINTS_IS PRIMARY KEY (APPLICATION_NO)
);

CREATE TABLE TB_CHECK_POINTS_IU (
  APPLICATION_NO VARCHAR2(30 BYTE) NOT NULL,
  EPROZ00800 VARCHAR2(2 BYTE) DEFAULT 'N',
  EPROISU0110 VARCHAR2(2 BYTE) DEFAULT 'N',
  EPROISU0120 VARCHAR2(2 BYTE) DEFAULT 'N',
  EPROISU0130 VARCHAR2(2 BYTE) DEFAULT 'N',
  EPROISU0160 VARCHAR2(2 BYTE) DEFAULT 'N',
  CONSTRAINT PK_TB_CHECK_POINTS_IU PRIMARY KEY (APPLICATION_NO)
);

CREATE TABLE TB_CHECK_POINTS_CS (
  APPLICATION_NO VARCHAR2(30 BYTE) NOT NULL,
  EPROZ00800 VARCHAR2(2 BYTE) DEFAULT 'N',
  EPROCSU0110 VARCHAR2(2 BYTE) DEFAULT 'N',
  EPROCSU0120 VARCHAR2(2 BYTE) DEFAULT 'N',
  EPROCSU0130 VARCHAR2(2 BYTE) DEFAULT 'N',
  -- BP4: physical downstream 0150 key exists for CS.
  EPROCSU0150 VARCHAR2(2 BYTE) DEFAULT 'N',
  EPROCSU0160 VARCHAR2(2 BYTE) DEFAULT 'N',
  CONSTRAINT PK_TB_CHECK_POINTS_CS PRIMARY KEY (APPLICATION_NO)
);

CREATE TABLE TB_CHECK_POINTS_CU (
  APPLICATION_NO VARCHAR2(30 BYTE) NOT NULL,
  EPROZ00800 VARCHAR2(2 BYTE) DEFAULT 'N',
  EPROCSU0110 VARCHAR2(2 BYTE) DEFAULT 'N',
  EPROCSU0120 VARCHAR2(2 BYTE) DEFAULT 'N',
  EPROCSU0130 VARCHAR2(2 BYTE) DEFAULT 'N',
  EPROCSU0160 VARCHAR2(2 BYTE) DEFAULT 'N',
  CONSTRAINT PK_TB_CHECK_POINTS_CU PRIMARY KEY (APPLICATION_NO)
);

CREATE TABLE TB_LOAN_CONDITION_DETAIL (
  APPLICATION_NO VARCHAR2(30 BYTE) NOT NULL,
  CON_TYPE VARCHAR2(5 BYTE) NOT NULL,
  SEQNO NUMBER(3,0) NOT NULL,
  LOAN_PURPOSE VARCHAR2(2 BYTE),
  LOAN_PURPOSE_OTHER VARCHAR2(300 BYTE),
  LOAN_AMOUNT_CURRENCY VARCHAR2(3 BYTE),
  LOAN_AMOUNT NUMBER(17,2),
  FACILITY_TYPE VARCHAR2(2 BYTE),
  FACILITY_TYPE_OTHER VARCHAR2(150 BYTE),
  REPAYMENT_MODE VARCHAR2(2 BYTE),
  REPAYMENT_MODE_OTHER VARCHAR2(600 BYTE),
  REPAYMENT_FREQUENCY VARCHAR2(150 BYTE),
  GRACE_PERIOD NUMBER(3,0),
  TENOR NUMBER(3,0),
  RATE_TYPE VARCHAR2(1 BYTE),
  FIX_RATE NUMBER(4,2),
  TIER_RATE_S1 NUMBER(3,0),
  TIER_RATE_E1 NUMBER(3,0),
  TIER_RATE_1 NUMBER(4,2),
  TIER_RATE_S2 NUMBER(3,0),
  TIER_RATE_E2 NUMBER(3,0),
  TIER_RATE_2 NUMBER(4,2),
  TIER_RATE_S3 NUMBER(3,0),
  TIER_RATE_E3 NUMBER(3,0),
  TIER_RATE_3 NUMBER(4,2),
  BASE_RATE_PLUS NUMBER(4,2),
  FD_RATE NUMBER(4,2),
  CONSTRAINT PK_TB_LOAN_CONDITION_DETAIL PRIMARY KEY (APPLICATION_NO, CON_TYPE, SEQNO)
);

CREATE TABLE TB_LOAN_CONDITION_FEE (
  APPLICATION_NO VARCHAR2(30 BYTE) NOT NULL,
  CON_TYPE VARCHAR2(5 BYTE) NOT NULL,
  FEE_1 NUMBER(3,2),
  FEE_2 NUMBER(3,2),
  FEE_2_MONTH_START VARCHAR2(3 BYTE),
  FEE_2_MONTH VARCHAR2(3 BYTE),
  FEE_2_2 NUMBER(3,2),
  FEE_2_2_MONTH_START VARCHAR2(3 BYTE),
  FEE_2_2_MONTH VARCHAR2(3 BYTE),
  FEE_2_3 NUMBER(3,2),
  FEE_2_3_MONTH_START VARCHAR2(3 BYTE),
  FEE_2_3_MONTH VARCHAR2(3 BYTE),
  FEE_3 NUMBER(3,2),
  FEE_4 NUMBER(3,2),
  FEE_5 NUMBER(3,2),
  CBC_FEE VARCHAR2(300 BYTE),
  OTHER_FEE_1 VARCHAR2(3333 BYTE),
  OTHER_FEE_2 VARCHAR2(3333 BYTE),
  OTHER_FEE_3 VARCHAR2(3333 BYTE),
  UPD_TIME TIMESTAMP(6),
  ORI_APPLICATION_NO VARCHAR2(30 BYTE),
  ORI_CON_TYPE VARCHAR2(5 BYTE),
  CONSTRAINT PK_TB_LOAN_CONDITION_FEE PRIMARY KEY (APPLICATION_NO, CON_TYPE)
);

CREATE TABLE TB_MAIN_BORROWER_PERSONAL_INFO (
  APPLICATION_NO VARCHAR2(30 BYTE) NOT NULL,
  MAIN_BORROWER_NAME VARCHAR2(50 BYTE) NOT NULL,
  IS_ANY_GUARANTOR VARCHAR2(2 BYTE),
  IS_ANY_COLLATERAL_PROVIDER VARCHAR2(2 BYTE),
  CONSTRAINT PK_TB_MAIN_BORROWER_PERSONAL_INFO PRIMARY KEY (APPLICATION_NO, MAIN_BORROWER_NAME)
);

CREATE TABLE TB_MAIN_BORROWER_INFO_CORP (
  APPLICATION_NO VARCHAR2(30 BYTE) NOT NULL,
  MAIN_BORROWER_NAME VARCHAR2(100 BYTE) NOT NULL,
  ESTABLISH_DATE DATE NOT NULL,
  IS_ANY_GUARANTOR VARCHAR2(2 BYTE),
  IS_ANY_COLLATERAL_PROVIDER VARCHAR2(2 BYTE),
  CONSTRAINT PK_TB_MAIN_BORROWER_INFO_CORP PRIMARY KEY (APPLICATION_NO, MAIN_BORROWER_NAME, ESTABLISH_DATE)
);

CREATE TABLE TB_GUARANTOR_INFO (
  APPLICATION_NO VARCHAR2(30 BYTE) NOT NULL,
  GUARANTOR_NAME VARCHAR2(50 BYTE) NOT NULL,
  DATE_OF_BIRTH DATE NOT NULL,
  DATA_SEQ NUMBER(2,0) NOT NULL,
  CR_DEL VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL,
  CONSTRAINT PK_TB_GUARANTOR_INFO PRIMARY KEY (APPLICATION_NO, GUARANTOR_NAME, DATE_OF_BIRTH, DATA_SEQ)
);

CREATE TABLE TB_GUARANTOR_INFO_CORP (
  APPLICATION_NO VARCHAR2(30 BYTE) NOT NULL,
  DATA_SEQ NUMBER(2,0) NOT NULL,
  GUARANTOR_NAME VARCHAR2(100 BYTE) NOT NULL,
  ESTABLISH_DATE DATE NOT NULL,
  CR_DEL VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL,
  CONSTRAINT PK_TB_GUARANTOR_INFO_CORP PRIMARY KEY (APPLICATION_NO, DATA_SEQ, GUARANTOR_NAME, ESTABLISH_DATE)
);

CREATE TABLE TB_COLL_INFO (
  APPLICATION_NO VARCHAR2(30 BYTE) NOT NULL,
  COLL_DATA_SEQ NUMBER(3,0) NOT NULL,
  CR_DEL VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL,
  CONSTRAINT PK_TB_COLL_INFO PRIMARY KEY (APPLICATION_NO, COLL_DATA_SEQ)
);

CREATE TABLE TB_COLL_VALUE_INFO (
  APPLICATION_NO VARCHAR2(30 BYTE) NOT NULL,
  COLL_DATA_SEQ NUMBER(3,0) NOT NULL,
  CONSTRAINT PK_TB_COLL_VALUE_INFO PRIMARY KEY (APPLICATION_NO, COLL_DATA_SEQ)
);

CREATE TABLE TB_COLL_LTV (
  APPLICATION_NO VARCHAR2(30 BYTE) NOT NULL,
  PRO_COVERAGE_LTV NUMBER(5,2),
  DEVIATION VARCHAR2(2 BYTE),
  DEVIATION_MEMO LONG,
  TOTAL_SUG_VALUE NUMBER(19,2),
  DEVIATION_1 VARCHAR2(1 BYTE),
  DEVIATION_2 VARCHAR2(1 BYTE),
  DEVIATION_3 VARCHAR2(1 BYTE),
  DEVIATION_4 VARCHAR2(1 BYTE),
  DEVIATION_OTHER VARCHAR2(500 BYTE),
  SG_COVERAGE_LTV NUMBER(5,2),
  CR_DEVIATION_1 VARCHAR2(1 BYTE),
  CONSTRAINT PK_TB_COLL_LTV PRIMARY KEY (APPLICATION_NO)
);

CREATE TABLE TB_COLL_PROVIDER_INFO (
  APPLICATION_NO VARCHAR2(30 BYTE) NOT NULL,
  PROVIDER_NAME VARCHAR2(50 BYTE) NOT NULL,
  COLL_DATA_SEQ NUMBER(3,0) NOT NULL,
  DATA_SEQ NUMBER(2,0) NOT NULL,
  DATE_OF_BIRTH DATE NOT NULL,
  CR_DEL VARCHAR2(1 BYTE) DEFAULT 'N' NOT NULL,
  CONSTRAINT PK_TB_COLL_PROVIDER_INFO PRIMARY KEY (APPLICATION_NO, PROVIDER_NAME, COLL_DATA_SEQ, DATA_SEQ, DATE_OF_BIRTH)
);

CREATE TABLE TB_COLL_TITLE_REGIS_OWNER (
  APPLICATION_NO VARCHAR2(30 BYTE) NOT NULL,
  COLL_DATA_SEQ NUMBER(3,0) NOT NULL,
  COLL_DOC_SEQ NUMBER(3,0) NOT NULL,
  COLL_REGIS_CATE VARCHAR2(5 BYTE) NOT NULL,
  DATA_SEQ NUMBER(3,0) NOT NULL,
  CONSTRAINT PK_TB_COLL_TITLE_REGIS_OWNER PRIMARY KEY (APPLICATION_NO, COLL_DATA_SEQ, COLL_DOC_SEQ, COLL_REGIS_CATE, DATA_SEQ)
);

CREATE TABLE TB_COLL_SITE_VISIT (
  APPLICATION_NO VARCHAR2(30 BYTE) NOT NULL,
  COLL_DATA_SEQ NUMBER(3,0) NOT NULL,
  CONSTRAINT PK_TB_COLL_SITE_VISIT PRIMARY KEY (APPLICATION_NO, COLL_DATA_SEQ)
);

CREATE TABLE TB_COLL_TITLE_DETAIL (
  APPLICATION_NO VARCHAR2(30 BYTE) NOT NULL,
  COLL_DATA_SEQ NUMBER(3,0) NOT NULL,
  COLL_DOC_SEQ NUMBER(3,0) NOT NULL,
  CONSTRAINT PK_TB_COLL_TITLE_DETAIL PRIMARY KEY (APPLICATION_NO, COLL_DATA_SEQ, COLL_DOC_SEQ)
);

CREATE TABLE TB_COLL_VALUE_DETAIL (
  APPLICATION_NO VARCHAR2(30 BYTE) NOT NULL,
  COLL_DATA_SEQ NUMBER(3,0) NOT NULL,
  COMP_SEQ NUMBER(2,0) NOT NULL,
  VAL_SEQ NUMBER(2,0) NOT NULL,
  CONSTRAINT PK_TB_COLL_VALUE_DETAIL PRIMARY KEY (APPLICATION_NO, COLL_DATA_SEQ, COMP_SEQ, VAL_SEQ)
);

CREATE TABLE TB_INSPE_AO (
  APPLICATION_NO VARCHAR2(30 BYTE) NOT NULL,
  INSPE_AO_CODE VARCHAR2(7 BYTE) NOT NULL,
  INSPE_AO_NAME VARCHAR2(50 BYTE),
  COLL_DATA_SEQ NUMBER(3,0) NOT NULL,
  INSPE_AO_BRN_CODE VARCHAR2(5 BYTE),
  CONSTRAINT PK_TB_INSPE_AO PRIMARY KEY (APPLICATION_NO, INSPE_AO_CODE, COLL_DATA_SEQ)
);

CREATE TABLE TB_CROSS_CHARGE_DETAIL (
  APPLICATION_NO VARCHAR2(30 BYTE) NOT NULL,
  COLL_DATA_SEQ NUMBER(3,0) NOT NULL,
  CROSS_CHARGE_SEQ NUMBER(3,0) NOT NULL,
  CROSS_APPLICATION_NO VARCHAR2(30 BYTE),
  CONSTRAINT PK_TB_CROSS_CHARGE_DETAIL PRIMARY KEY (APPLICATION_NO, COLL_DATA_SEQ, CROSS_CHARGE_SEQ)
);

CREATE TABLE TB_API_AUTH (
  API_ID VARCHAR2(100 BYTE) NOT NULL,
  ROLE VARCHAR2(100 BYTE) NOT NULL,
  REF_FUNCTION_ID VARCHAR2(100 BYTE),
  UPDATE_USER VARCHAR2(10 BYTE),
  UPDATE_DATE DATE,
  CONSTRAINT PK_TB_API_AUTH PRIMARY KEY (API_ID)
);
