-- SRS schema excerpt for EPROC00118 Corporate Scorecard.
-- excerpt: only SRS-relevant columns shown.
-- Source: docs/db-diff/02_tables/*.md as local snapshot.
-- Change hints:
-- DB-D1 carried: TB_CORP_SCRCARD active/exact, copied from legacy data.
-- DB-D2 changed: TB_SCORE_CARD_PARAM_DETAIL active/exact, transpose_method=rewritten fixed parameters.
-- DB-D3 carried: TB_LON_SUMMARY_INFO.CR_SCORE_CARD_COMPLETED is physical VARCHAR2(2 BYTE);
-- first char is corporate scorecard status, second char is other scorecard status.
-- DB-D4 changed: legacy TB_CHECK_POINT_CORP, TB_CHECK_POINT_CU, TB_CHECK_POINT_RC_CORP, TB_CHECK_POINT_RC_CU are removed_or_unused.
-- DB-D4 new targets: TB_CHECK_POINTS_CS and TB_CHECK_POINTS_CU with EPROC00118 column.
-- DB-D5 resolved: RC legacy EPROC0_0218 reuses EPROC00118 in TB_CHECK_POINTS_CS/CU.
-- DB-D6 carried: TB_MAIN_BORROWER_INFO_CORP.MAIN_BORROWER_NAME is exposed by the info API.
-- AUTH-D1 carried external dependency: TB_API_AUTH must contain exact endpoint keys
-- epl-sele-c0-corporateScorecard-list, epl-info-c0-corporateScorecard,
-- epl-calc-c0-corporateScorecard, and epl-save-c0-corporateScorecard.

CREATE TABLE TB_CORP_SCRCARD (
  APPLICATION_NO VARCHAR2(30 BYTE) NOT NULL,
  AO_DEFAULT_DAY_FLG VARCHAR2(2 BYTE),
  AO_AGE_CODE VARCHAR2(2 BYTE),
  AO_AGE_SCR NUMBER(3,0),
  AO_GUAR_AGE_CODE VARCHAR2(2 BYTE),
  AO_GUAR_AGE_SCR NUMBER(3,0),
  AO_COMP_TYPE_CODE VARCHAR2(2 BYTE),
  AO_COMP_TYPE_SCR NUMBER(3,0),
  AO_INDUSTRY_CODE VARCHAR2(2 BYTE),
  AO_INDUSTRY_SCR NUMBER(3,0),
  AO_YEAR_OP_CODE VARCHAR2(2 BYTE),
  AO_YEAR_OP_SCR NUMBER(3,0),
  AO_LOAN_PURPOSE_CODE VARCHAR2(2 BYTE),
  AO_LOAN_PURPOSE_SCR NUMBER(3,0),
  AO_REPAYMENT_S_CODE VARCHAR2(2 BYTE),
  AO_REPAYMENT_S_SCR NUMBER(3,0),
  AO_K_SCORE_CODE VARCHAR2(2 BYTE),
  AO_K_SCORE_SCR NUMBER(3,0),
  AO_MAX_OVERDUE_CODE VARCHAR2(2 BYTE),
  AO_MAX_OVERDUE_SCR NUMBER(3,0),
  AO_TRANS_12MON_CODE VARCHAR2(2 BYTE),
  AO_TRANS_12MON_SCR NUMBER(3,0),
  AO_SUBS_REPAYMENT_S_CODE VARCHAR2(2 BYTE),
  AO_SUBS_REPAYMENT_S_SCR NUMBER(3,0),
  AO_COMP_POSITIVE_CODE VARCHAR2(2 BYTE),
  AO_COMP_POSITIVE_SCR NUMBER(3,0),
  AO_GROWTH_RATIO_CODE VARCHAR2(2 BYTE),
  AO_GROWTH_RATIO_SCR NUMBER(3,0),
  AO_PM_GROWTH_RATIO_CODE VARCHAR2(2 BYTE),
  AO_PM_GROWTH_RATIO_SCR NUMBER(3,0),
  AO_CUR_RATIO_CODE VARCHAR2(2 BYTE),
  AO_CUR_RATIO_SCR NUMBER(3,0),
  AO_DE_RATIO_CODE VARCHAR2(2 BYTE),
  AO_DE_RATIO_SCR NUMBER(3,0),
  AO_AP_CODE VARCHAR2(2 BYTE),
  AO_AP_SCR NUMBER(3,0),
  AO_AR_CODE VARCHAR2(2 BYTE),
  AO_AR_SCR NUMBER(3,0),
  AO_INVENTORY_CODE VARCHAR2(2 BYTE),
  AO_INVENTORY_SCR NUMBER(3,0),
  AO_CMP_TOT_ASSET_CODE VARCHAR2(2 BYTE),
  AO_CMP_TOT_ASSET_SCR NUMBER(3,0),
  AO_TOTAL_LOAN_AMT_CODE VARCHAR2(2 BYTE),
  AO_TOTAL_LOAN_AMT_SCR NUMBER(3,0),
  AO_DEBT_RATIO_CODE VARCHAR2(2 BYTE),
  AO_DEBT_RATIO_SCR NUMBER(3,0),
  AO_RISK_LEVEL VARCHAR2(7 BYTE),
  AO_CODE VARCHAR2(7 BYTE),
  AO_NAME VARCHAR2(50 BYTE),
  AO_DATE TIMESTAMP(6),
  CR_DEFAULT_DAY_FLG VARCHAR2(2 BYTE),
  CR_AGE_CODE VARCHAR2(2 BYTE),
  CR_AGE_SCR NUMBER(3,0),
  CR_GUAR_AGE_CODE VARCHAR2(2 BYTE),
  CR_GUAR_AGE_SCR NUMBER(3,0),
  CR_COMP_TYPE_CODE VARCHAR2(2 BYTE),
  CR_COMP_TYPE_SCR NUMBER(3,0),
  CR_INDUSTRY_CODE VARCHAR2(2 BYTE),
  CR_INDUSTRY_SCR NUMBER(3,0),
  CR_YEAR_OP_CODE VARCHAR2(2 BYTE),
  CR_YEAR_OP_SCR NUMBER(3,0),
  CR_LOAN_PURPOSE_CODE VARCHAR2(2 BYTE),
  CR_LOAN_PURPOSE_SCR NUMBER(3,0),
  CR_REPAYMENT_S_CODE VARCHAR2(2 BYTE),
  CR_REPAYMENT_S_SCR NUMBER(3,0),
  CR_K_SCORE_CODE VARCHAR2(2 BYTE),
  CR_K_SCORE_SCR NUMBER(3,0),
  CR_MAX_OVERDUE_CODE VARCHAR2(2 BYTE),
  CR_MAX_OVERDUE_SCR NUMBER(3,0),
  CR_TRANS_12MON_CODE VARCHAR2(2 BYTE),
  CR_TRANS_12MON_SCR NUMBER(3,0),
  CR_SUBS_REPAYMENT_S_CODE VARCHAR2(2 BYTE),
  CR_SUBS_REPAYMENT_S_SCR NUMBER(3,0),
  CR_COMP_POSITIVE_CODE VARCHAR2(2 BYTE),
  CR_COMP_POSITIVE_SCR NUMBER(3,0),
  CR_GROWTH_RATIO_CODE VARCHAR2(2 BYTE),
  CR_GROWTH_RATIO_SCR NUMBER(3,0),
  CR_PM_GROWTH_RATIO_CODE VARCHAR2(2 BYTE),
  CR_PM_GROWTH_RATIO_SCR NUMBER(3,0),
  CR_CUR_RATIO_CODE VARCHAR2(2 BYTE),
  CR_CUR_RATIO_SCR NUMBER(3,0),
  CR_DE_RATIO_CODE VARCHAR2(2 BYTE),
  CR_DE_RATIO_SCR NUMBER(3,0),
  CR_AP_CODE VARCHAR2(2 BYTE),
  CR_AP_SCR NUMBER(3,0),
  CR_AR_CODE VARCHAR2(2 BYTE),
  CR_AR_SCR NUMBER(3,0),
  CR_INVENTORY_CODE VARCHAR2(2 BYTE),
  CR_INVENTORY_SCR NUMBER(3,0),
  CR_CMP_TOT_ASSET_CODE VARCHAR2(2 BYTE),
  CR_CMP_TOT_ASSET_SCR NUMBER(3,0),
  CR_TOTAL_LOAN_AMT_CODE VARCHAR2(2 BYTE),
  CR_TOTAL_LOAN_AMT_SCR NUMBER(3,0),
  CR_DEBT_RATIO_CODE VARCHAR2(2 BYTE),
  CR_DEBT_RATIO_SCR NUMBER(3,0),
  CR_RISK_LEVEL VARCHAR2(7 BYTE),
  CR_CODE VARCHAR2(7 BYTE),
  CR_NAME VARCHAR2(50 BYTE),
  CR_DATE TIMESTAMP(6),
  CR_COMMENT VARCHAR2(3000 BYTE),
  CR_COMMENT_DATE TIMESTAMP(6),
  AO_CUR_RATIO NUMBER(3,2),
  CR_CUR_RATIO NUMBER(3,2),
  AO_DE_RATIO NUMBER(9,2),
  CR_DE_RATIO NUMBER(9,2),
  AO_CMP_TOT_ASSET NUMBER(19,2),
  CR_CMP_TOT_ASSET NUMBER(19,2),
  AO_TOTAL_LOAN_AMT NUMBER(19,2),
  CR_TOTAL_LOAN_AMT NUMBER(19,2),
  AO_DEBT_RATIO NUMBER(6,2),
  CR_DEBT_RATIO NUMBER(6,2),
  AO_SCORE NUMBER(7,2),
  CR_SCORE NUMBER(7,2),
  CONSTRAINT PK_TB_CORP_SCRCARD PRIMARY KEY (APPLICATION_NO)
);

CREATE TABLE TB_SCORE_CARD_PARAM_DETAIL (
  DOC_ID VARCHAR2(20 BYTE) NOT NULL,
  VAR_NAME VARCHAR2(30 BYTE) NOT NULL,
  VAR_CODE VARCHAR2(3 BYTE) NOT NULL,
  LOW_RANGE NUMBER(11,2),
  UP_RANGE NUMBER(12,2),
  -- SCORE is text in DB; BE converts to number for sum and rejects nonnumeric seed as MSG_QUERY_FAIL.
  SCORE VARCHAR2(10 BYTE),
  VAR_DESC VARCHAR2(100 BYTE),
  VAR_ORDER NUMBER(3,0),
  ST_DATE DATE,
  END_DATE DATE
);

CREATE TABLE TB_LON_SUMMARY_INFO (
  APPLICATION_NO VARCHAR2(30 BYTE) NOT NULL,
  APPLICATION_DATE TIMESTAMP(6),
  LON_ATTRIBUTE VARCHAR2(2 BYTE),
  SECURE_ATTRIBUTE VARCHAR2(2 BYTE),
  CR_SCORE_CARD_COMPLETED VARCHAR2(2 BYTE),
  CONSTRAINT PK_TB_LON_SUMMARY_INFO PRIMARY KEY (APPLICATION_NO)
);

CREATE TABLE TB_MAIN_BORROWER_INFO_CORP (
  APPLICATION_NO VARCHAR2(30 BYTE) NOT NULL,
  MAIN_BORROWER_NAME VARCHAR2(100 BYTE) NOT NULL,
  ESTABLISH_DATE DATE NOT NULL,
  CONSTRAINT PK_TB_MAIN_BORROWER_INFO_CORP PRIMARY KEY (APPLICATION_NO, MAIN_BORROWER_NAME, ESTABLISH_DATE)
);

CREATE TABLE TB_CHECK_POINTS_CS (
  APPLICATION_NO VARCHAR2(30 BYTE) NOT NULL,
  EPROC00118 VARCHAR2(2 BYTE) DEFAULT 'N',
  CONSTRAINT PK_TB_CHECK_POINTS_CS PRIMARY KEY (APPLICATION_NO)
);

CREATE TABLE TB_CHECK_POINTS_CU (
  APPLICATION_NO VARCHAR2(30 BYTE) NOT NULL,
  EPROC00118 VARCHAR2(2 BYTE) DEFAULT 'N',
  CONSTRAINT PK_TB_CHECK_POINTS_CU PRIMARY KEY (APPLICATION_NO)
);
