-- EPROCSU0170 SRS schema slice.
-- Purpose: document touched tables/columns and DB reconcile deltas for review.
-- This is not a production migration script.

CREATE TABLE TB_LON_SUMMARY_INFO (
    APPLICATION_NO VARCHAR2(30) NOT NULL,
    LON_TYPE_CODE VARCHAR2(5),
    APPLICATION_DATE TIMESTAMP,
    DECISION_DATE TIMESTAMP,
    CASE_PROGRESS VARCHAR2(5),
    LON_ATTRIBUTE VARCHAR2(2),
    SECURE_ATTRIBUTE VARCHAR2(2),
    AO_ASSISTANT_CODE VARCHAR2(7),
    AO_CODE VARCHAR2(7),
    REF_APPLICATION_NO VARCHAR2(30),
    CR_CODE VARCHAR2(7),
    CURRENT_USER_ID VARCHAR2(7),
    IS_LLC VARCHAR2(1),
    IS_LC VARCHAR2(1),
    CR_RELATED_PARTY_COMPLETED VARCHAR2(1),
    CR_SCORE_CARD_COMPLETED VARCHAR2(2),
    FIN_APPR_LEVEL VARCHAR2(2),
    CA_CODE VARCHAR2(5),
    SYS_APPR_LEVEL VARCHAR2(4),
    CR_APPR_LEVEL VARCHAR2(4),
    APP_CON_TYPE VARCHAR2(5),
    CONSTRAINT PK_TB_LON_SUMMARY_INFO PRIMARY KEY (APPLICATION_NO)
);

CREATE TABLE TB_APP_HISTORY (
    APPLICATION_NO VARCHAR2(30) NOT NULL,
    APP_PROCESS_CODE VARCHAR2(5) NOT NULL,
    PROCESS_EMP_CODE VARCHAR2(7),
    PROCESS_EMP_NAME VARCHAR2(50),
    PROCESS_BRANCH_CODE VARCHAR2(5),
    PROCESS_BRANCH_NAME VARCHAR2(50),
    PROCESS_DATE TIMESTAMP NOT NULL,
    CONSTRAINT PK_TB_APP_HISTORY PRIMARY KEY (APPLICATION_NO, APP_PROCESS_CODE, PROCESS_DATE)
);

CREATE TABLE TB_LOAN_CONDITION_DETAIL (
    APPLICATION_NO VARCHAR2(30) NOT NULL,
    CON_TYPE VARCHAR2(5) NOT NULL,
    SEQNO NUMBER(3,0) NOT NULL,
    LOAN_PURPOSE VARCHAR2(2),
    LOAN_PURPOSE_OTHER VARCHAR2(300),
    SUB_LOAN_PURPOSE VARCHAR2(2),
    SUB_LOAN_PURPOSE_OTHER VARCHAR2(300),
    LOAN_AMOUNT_CURRENCY VARCHAR2(3),
    LOAN_AMOUNT NUMBER(17,2),
    LOAN_TYPE VARCHAR2(2),
    FACILITY_TYPE VARCHAR2(2),
    FACILITY_TYPE_OTHER VARCHAR2(150),
    REPAYMENT_MODE VARCHAR2(2),
    REPAYMENT_MODE_OTHER VARCHAR2(600),
    REPAYMENT_FREQUENCY VARCHAR2(150),
    REPAYMENT_FREQUENCY_OTHER VARCHAR2(150),
    GRACE_PERIOD NUMBER(3,0),
    TENOR NUMBER(3,0),
    RATE_TYPE VARCHAR2(1),
    FIX_RATE NUMBER(4,2),
    TIER_RATE_S1 NUMBER(3,0),
    TIER_RATE_E1 NUMBER(3,0),
    TIER_RATE_1 NUMBER(4,2),
    TIER_RATE_S2 NUMBER(3,0),
    TIER_RATE_E2 NUMBER(3,0),
    TIER_RATE_2 NUMBER(4,2),
    TIER_RATE_S3 NUMBER(3,0),
    TIER_RATE_E3 NUMBER(3,0),
    TIER_RATE_3 NUMBER(4,2),
    UPD_TIME TIMESTAMP,
    ORI_APPLICATION_NO VARCHAR2(30),
    ORI_CON_TYPE VARCHAR2(5),
    ORI_SEQNO NUMBER(3,0),
    BASE_RATE_PLUS NUMBER(4,2),
    FD_RATE NUMBER(4,2),
    LOAN_SECTOR_CODE VARCHAR2(3),
    LOAN_SUB_SECTOR_CODE VARCHAR2(5),
    LOAN_SECTION_CODE VARCHAR2(7),
    CONSTRAINT PK_TB_LOAN_CONDITION_DETAIL PRIMARY KEY (APPLICATION_NO, CON_TYPE, SEQNO)
);

CREATE TABLE TB_LOAN_CONDITION_FEE (
    APPLICATION_NO VARCHAR2(30) NOT NULL,
    CON_TYPE VARCHAR2(5) NOT NULL,
    FEE_1 NUMBER(3,2),
    FEE_2 NUMBER(3,2),
    FEE_2_MONTH_START VARCHAR2(3),
    FEE_2_MONTH VARCHAR2(3),
    FEE_2_2 NUMBER(3,2),
    FEE_2_2_MONTH_START VARCHAR2(3),
    FEE_2_2_MONTH VARCHAR2(3),
    FEE_2_3 NUMBER(3,2),
    FEE_2_3_MONTH_START VARCHAR2(3),
    FEE_2_3_MONTH VARCHAR2(3),
    FEE_3 NUMBER(3,2),
    FEE_4 NUMBER(3,2),
    FEE_5 NUMBER(3,2),
    CBC_FEE VARCHAR2(300),
    OTHER_FEE_1 VARCHAR2(3333),
    OTHER_FEE_2 VARCHAR2(3333),
    OTHER_FEE_3 VARCHAR2(3333),
    UPD_TIME TIMESTAMP,
    ORI_APPLICATION_NO VARCHAR2(30),
    ORI_CON_TYPE VARCHAR2(5),
    CONSTRAINT PK_TB_LOAN_CONDITION_FEE PRIMARY KEY (APPLICATION_NO, CON_TYPE)
);

CREATE TABLE TB_LOAN_EVAL_COMMENT (
    APPLICATION_NO VARCHAR2(30) NOT NULL,
    TYPE VARCHAR2(5) NOT NULL,
    ROLE_ID VARCHAR2(5),
    COMMEMT1 VARCHAR2(3333),
    COMMENT2 VARCHAR2(3333),
    COMMENT3 VARCHAR2(3333),
    TMP_COMMENT1 VARCHAR2(3333),
    TMP_COMMENT2 VARCHAR2(3333),
    TMP_COMMENT3 VARCHAR2(3333),
    UPLOAD_FILE_PATH VARCHAR2(300),
    UPLOAD_FILE_NAME VARCHAR2(50),
    UPD_USER VARCHAR2(5),
    UPD_TIME TIMESTAMP,
    MEETING_DATE DATE,
    DATA_SEQ NUMBER(2,0) NOT NULL,
    UPD_NAME VARCHAR2(50),
    PROXY_ID VARCHAR2(5),
    CONSTRAINT PK_TB_LOAN_EVAL_COMMENT PRIMARY KEY (APPLICATION_NO, TYPE, DATA_SEQ)
);

CREATE TABLE TB_COLL_LTV (
    APPLICATION_NO VARCHAR2(30) NOT NULL,
    PRO_COVERAGE_LTV NUMBER(5,2),
    DEVIATION VARCHAR2(2),
    DEVIATION_MEMO LONG,
    TOTAL_SUG_VALUE NUMBER(19,2),
    DEVIATION_1 VARCHAR2(1),
    DEVIATION_2 VARCHAR2(1),
    DEVIATION_3 VARCHAR2(1),
    DEVIATION_4 VARCHAR2(1),
    DEVIATION_OTHER VARCHAR2(500),
    SG_COVERAGE_LTV NUMBER(5,2),
    CR_DEVIATION_1 VARCHAR2(1),
    CONSTRAINT PK_TB_COLL_LTV PRIMARY KEY (APPLICATION_NO)
);

CREATE TABLE TB_RETURN_INFO (
    APPLICATION_NO VARCHAR2(30) NOT NULL,
    SEQNO NUMBER(3,0) NOT NULL,
    RETURN_CODE VARCHAR2(1000),
    AMEND_DOCUMENTS_MEMO VARCHAR2(3333),
    AMEND_PROPOSAL_INFO_MEMO VARCHAR2(3333),
    RETURN_STATUS VARCHAR2(1) DEFAULT 'N',
    CR_EMP_ID VARCHAR2(10),
    UPDATE_DATE TIMESTAMP,
    RETURN_DATE TIMESTAMP,
    CONSTRAINT PK_TB_RETURN_INFO PRIMARY KEY (APPLICATION_NO, SEQNO)
);

CREATE TABLE TB_CAN_REASON (
    APPLICATION_NO VARCHAR2(30) NOT NULL,
    REASON_CODE VARCHAR2(100),
    OTH_REASON VARCHAR2(100),
    CAN_DATE TIMESTAMP,
    CONSTRAINT PK_TB_CAN_REASON PRIMARY KEY (APPLICATION_NO)
);

CREATE TABLE TB_NOTIFICATION_INFO (
    NO NUMBER DEFAULT OVSLXLON01."EMAIL_SERIAL"."NEXTVAL" NOT NULL,
    APPLICATION_NO VARCHAR2(30) NOT NULL,
    RECEIVER_ID VARCHAR2(5) NOT NULL,
    RECEIVER_NAME VARCHAR2(50),
    RECEIVER_EMAIL VARCHAR2(100),
    SUBJECT VARCHAR2(100),
    CONTENT VARCHAR2(1000),
    STATUS VARCHAR2(1) DEFAULT 'N',
    CREATE_ID VARCHAR2(10) NOT NULL,
    CREATE_DATE TIMESTAMP NOT NULL,
    UPDATE_ID VARCHAR2(10),
    UPDATE_DATE TIMESTAMP,
    CONSTRAINT PK_TB_NOTIFICATION_INFO PRIMARY KEY (NO, APPLICATION_NO)
);

CREATE TABLE TB_REVISED_ITEM (
    APPLICATION_NO VARCHAR2(30) NOT NULL,
    REASON_MEMO VARCHAR2(4000),
    UPD_DATE DATE,
    ITEM1 VARCHAR2(1),
    ITEM2 VARCHAR2(1),
    ITEM3 VARCHAR2(1),
    ITEM4 VARCHAR2(1),
    ITEM5 VARCHAR2(1),
    ITEM6 VARCHAR2(1),
    ITEM7 VARCHAR2(1),
    ITEM8 VARCHAR2(1),
    ITEM9 VARCHAR2(1),
    ITEM10 VARCHAR2(1),
    ITEM11 VARCHAR2(1),
    ITEM12 VARCHAR2(1),
    ITEM13 VARCHAR2(1),
    ITEM14 VARCHAR2(1),
    CONSTRAINT PK_TB_REVISED_ITEM PRIMARY KEY (APPLICATION_NO)
);

CREATE TABLE TB_CHECK_POINTS_CS (
    APPLICATION_NO VARCHAR2(30) NOT NULL,
    EPROZ00800 VARCHAR2(2) DEFAULT 'N',
    EPROCSU0110 VARCHAR2(2) DEFAULT 'N',
    EPROCSU0120 VARCHAR2(2) DEFAULT 'N',
    EPROCSU0130 VARCHAR2(2) DEFAULT 'N',
    EPROCSU0140 VARCHAR2(2),
    EPROCSU0150 VARCHAR2(2) DEFAULT 'N',
    EPROC00115 VARCHAR2(2) DEFAULT 'N',
    EPROC00112 VARCHAR2(2) DEFAULT 'N',
    EPROC00116 VARCHAR2(2) DEFAULT 'N',
    EPROC00119 VARCHAR2(2) DEFAULT 'N',
    EPROC00117 VARCHAR2(2) DEFAULT 'N',
    EPROC00120 VARCHAR2(2) DEFAULT 'N',
    EPROC00118 VARCHAR2(2) DEFAULT 'N',
    EPROC00114 VARCHAR2(2) DEFAULT 'N',
    EPROCSU0160 VARCHAR2(2) DEFAULT 'N',
    CONSTRAINT PK_TB_CHECK_POINTS_CS PRIMARY KEY (APPLICATION_NO)
);

CREATE TABLE TB_CHECK_POINTS_CU (
    APPLICATION_NO VARCHAR2(30) NOT NULL,
    EPROZ00800 VARCHAR2(2) DEFAULT 'N',
    EPROCSU0110 VARCHAR2(2) DEFAULT 'N',
    EPROCSU0120 VARCHAR2(2) DEFAULT 'N',
    EPROCSU0130 VARCHAR2(2) DEFAULT 'N',
    EPROC00115 VARCHAR2(2) DEFAULT 'N',
    EPROC00112 VARCHAR2(2) DEFAULT 'N',
    EPROC00116 VARCHAR2(2) DEFAULT 'N',
    EPROC00119 VARCHAR2(2) DEFAULT 'N',
    EPROC00117 VARCHAR2(2) DEFAULT 'N',
    EPROC00120 VARCHAR2(2) DEFAULT 'N',
    EPROC00118 VARCHAR2(2) DEFAULT 'N',
    EPROCSU0160 VARCHAR2(2) DEFAULT 'N',
    CONSTRAINT PK_TB_CHECK_POINTS_CU PRIMARY KEY (APPLICATION_NO)
);

CREATE TABLE TB_API_AUTH (
    API_ID VARCHAR2(100) NOT NULL,
    ROLE VARCHAR2(100) NOT NULL,
    REF_FUNCTION_ID VARCHAR2(100),
    UPDATE_USER VARCHAR2(10),
    UPDATE_DATE DATE,
    CONSTRAINT PK_TB_API_AUTH PRIMARY KEY (API_ID)
);

-- Legacy removed-or-unused checkpoint tables referenced by PRD parity:
-- TB_CHECK_POINT_CORP, TB_CHECK_POINT_RC_CORP, TB_CHECK_POINT_CU, TB_CHECK_POINT_RC_CU.

-- Delta DB-D1: TB_LON_SUMMARY_INFO active; source docs/db-diff/02_tables/TB_LON_SUMMARY_INFO.md:49,62-71,80; three-judge: (c) schema new as authority, code aligns behavior; carry.
-- Delta DB-D2: TB_CHECK_POINTS_CS/CU active but no EPROCSU0170 column in snapshot; source docs/db-diff/02_tables/TB_CHECK_POINTS_CS.md:38-53 and TB_CHECK_POINTS_CU.md:38-50; three-judge: (c) DB structure diff, behavior unresolved; RP19.
-- Delta DB-D3: TB_LOAN_EVAL_COMMENT usage_status=removed_or_unused while current code/PRD still use comments/files; source docs/db-diff/02_tables/TB_LOAN_EVAL_COMMENT.md:11-17,38-54; three-judge: (c) DB structure diff, probable contract drift; RP20.
-- Delta DB-D4: TB_LOAN_CONDITION_DETAIL/FEE active and used by save path; three-judge: (c) schema new as authority, behavior carry.
-- Delta DB-D5: TB_RETURN_INFO/TB_CAN_REASON active and use semicolon-joined code values; three-judge: (c) schema new as authority, behavior carry.
-- Delta DB-D6: TB_NOTIFICATION_INFO active, but email routing and AutoDisbursement strategy remain RP17; three-judge: (c) schema active, behavior pending.
-- Delta DB-D7: TB_API_AUTH exists, but service-level authorization proof remains RP24; three-judge: (c) schema active, behavior pending.
-- Delta DB-D8: TB_APP_HISTORY, TB_REVISED_ITEM, and TB_COLL_LTV are active support tables; three-judge: (c) schema new as authority, behavior carry.
-- Delta DB-D9: TB_UPLOAD_FILE_PTH is active in db-diff but not selected as authoritative EPROCSU0170 LLC file metadata target; three-judge: (c) schema active, behavior not selected; RP20.
