-- SRS schema snapshot for EPROZ00100.
-- Source: local docs/db-schema/02_tables/*.md. This is not a migration script.
-- Delta notes:
-- DB-D1/DB-D2: reasonCode maxLength is 100, matching TB_DEL_REASON/TB_CLO_REASON.
-- DB-D3: new TB_APP_HISTORY snapshot wins; do not add legacy PROCESS_AGENT_CODE/NAME columns.
-- DB-D6: refactor epl-list-todolist v1.3 carries SOFR for list/query behavior, while this DDL stays aligned to the db-schema snapshot without a physical SOFR column.

CREATE TABLE TB_LON_SUMMARY_INFO (
  APPLICATION_NO VARCHAR2(30) NOT NULL,
  LON_TYPE_CODE VARCHAR2(5),
  APPLICATION_DATE TIMESTAMP(6),
  RECEIVED_DATE TIMESTAMP(6),
  DISTRIBUTION_DATE TIMESTAMP(6),
  DECISION_DATE TIMESTAMP(6),
  CASE_PROGRESS VARCHAR2(5),
  LON_ATTRIBUTE VARCHAR2(2),
  SECURE_ATTRIBUTE VARCHAR2(2),
  BRANCH_CODE VARCHAR2(10),
  CR_CODE VARCHAR2(7),
  CURRENT_USER_ID VARCHAR2(7),
  CA_CODE VARCHAR2(5),
  RE_DISTRIBUTION VARCHAR2(1) DEFAULT 'N',
  IS_AUTODIS VARCHAR2(2),
  CONSTRAINT PK_TB_LON_SUMMARY_INFO PRIMARY KEY (APPLICATION_NO)
);

CREATE TABLE TB_DEL_REASON (
  APPLICATION_NO VARCHAR2(30),
  REASON_CODE VARCHAR2(100),
  OTH_REASON VARCHAR2(100),
  DEL_DATE TIMESTAMP(6),
  CONSTRAINT PK_TB_DEL_REASON PRIMARY KEY (APPLICATION_NO)
);

CREATE TABLE TB_CLO_REASON (
  APPLICATION_NO VARCHAR2(30),
  REASON_CODE VARCHAR2(100),
  OTH_REASON VARCHAR2(100),
  CLOSE_DATE TIMESTAMP(6),
  CONSTRAINT PK_TB_CLO_REASON PRIMARY KEY (APPLICATION_NO)
);

CREATE TABLE TB_APP_HISTORY (
  APPLICATION_NO VARCHAR2(30) NOT NULL,
  APP_PROCESS_CODE VARCHAR2(5) NOT NULL,
  PROCESS_EMP_CODE VARCHAR2(7),
  PROCESS_EMP_NAME VARCHAR2(50),
  PROCESS_BRANCH_CODE VARCHAR2(5),
  PROCESS_BRANCH_NAME VARCHAR2(50),
  PROCESS_DATE TIMESTAMP(6) NOT NULL,
  CONSTRAINT PK_TB_APP_HISTORY PRIMARY KEY (APPLICATION_NO, APP_PROCESS_CODE, PROCESS_DATE)
);

CREATE TABLE TB_RELATED_PARTY_INFO (
  APPLICATION_NO VARCHAR2(30) NOT NULL,
  BORROWER_NAME VARCHAR2(50) NOT NULL,
  IS_MAIN_BORR VARCHAR2(1),
  IS_CUB_RELATED VARCHAR2(1),
  IS_CUBC_RELATED VARCHAR2(1),
  DATA_SEQ NUMBER(2) NOT NULL,
  IS_TCP VARCHAR2(1),
  CONSTRAINT PK_TB_RELATED_PARTY_INFO PRIMARY KEY (APPLICATION_NO, BORROWER_NAME, DATA_SEQ)
);

CREATE TABLE TB_LOAN_CONDITION_DETAIL (
  APPLICATION_NO VARCHAR2(30) NOT NULL,
  CON_TYPE VARCHAR2(5) NOT NULL,
  SEQNO NUMBER(3) NOT NULL,
  LOAN_AMOUNT_CURRENCY VARCHAR2(3),
  LOAN_AMOUNT NUMBER(17,2),
  LOAN_TYPE VARCHAR2(2),
  FACILITY_TYPE VARCHAR2(2),
  TENOR NUMBER(3),
  FIX_RATE NUMBER,
  BASE_RATE_PLUS NUMBER,
  FD_RATE NUMBER,
  CONSTRAINT PK_TB_LOAN_CONDITION_DETAIL PRIMARY KEY (APPLICATION_NO, CON_TYPE, SEQNO)
);

CREATE TABLE TB_EMP_PROXY (
  EMP_ID VARCHAR2(10) NOT NULL,
  PROXY_ID VARCHAR2(10),
  STR_TIME TIMESTAMP(6) NOT NULL,
  END_TIME TIMESTAMP(6),
  UPDATE_EMP_ID VARCHAR2(10),
  UPDATE_DATE TIMESTAMP(6),
  RETURN_CASE_TO_CA VARCHAR2(1) DEFAULT 'N',
  CONSTRAINT PK_TB_EMP_PROXY PRIMARY KEY (EMP_ID)
);

CREATE TABLE TB_PROCESS_CODE (
  APP_PROCESS_CODE VARCHAR2(5),
  APP_PROCESS_NAME VARCHAR2(200),
  PROCESS_DESC VARCHAR2(300),
  IS_SHOW VARCHAR2(1),
  PROCESS_TYPE VARCHAR2(2),
  CONSTRAINT PK_TB_PROCESS_CODE PRIMARY KEY (APP_PROCESS_CODE)
);

CREATE TABLE TB_ROLE_DEFINE (
  ROLE_ID VARCHAR2(3) NOT NULL,
  ROLE_NAME VARCHAR2(50),
  ROLE_DESC VARCHAR2(50),
  CONSTRAINT PK_TB_ROLE_DEFINE PRIMARY KEY (ROLE_ID)
);

CREATE TABLE TB_API_AUTH (
  API_ID VARCHAR2(100) NOT NULL,
  ROLE VARCHAR2(100) NOT NULL,
  REF_FUNCTION_ID VARCHAR2(100),
  UPDATE_USER VARCHAR2(10),
  UPDATE_DATE DATE,
  CONSTRAINT PK_TB_API_AUTH PRIMARY KEY (API_ID)
);
